// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const ac_width : i32 = 1024;
const ac_half_w : i32 = 512;
fn ac_in(px : i32, py : i32) -> i32 {
  let rx = ((((px * 222) - (py * 128)) / 256) + 4096);
  let ry = ((((px * 128) + (py * 222)) / 256) + 4096);
  if (((rx - ((rx / 20) * 20)) < 6)) {
  return 1;
  } else {
  if (((ry - ((ry / 20) * 20)) < 6)) {
  return 1;
  } else {
  return 0;
  }
  }
}
fn ac_in4(px : i32, py : i32) -> i32 {
  let rx = ((((px * 222) - (py * 128)) / 256) + 16384);
  let ry = ((((px * 128) + (py * 222)) / 256) + 16384);
  if (((rx - ((rx / 80) * 80)) < 24)) {
  return 1;
  } else {
  if (((ry - ((ry / 80) * 80)) < 24)) {
  return 1;
  } else {
  return 0;
  }
  }
}
fn ac_super(px__a : i32, py__a : i32, s__a : i32, acc__a : i32) -> i32 {
  var px = px__a;
  var py = py__a;
  var s = s__a;
  var acc = acc__a;
  loop {
    if ((s >= 16)) {
    return acc;
    } else {
    let dx = (s - ((s / 4) * 4));
    let dy = (s / 4);
    let _mv0 = px;
    let _mv1 = py;
    let _mv2 = (s + 1);
    let _mv3 = (acc + ac_in4(((px * 4) + dx), ((py * 4) + dy)));
    px = _mv0;
    py = _mv1;
    s = _mv2;
    acc = _mv3;
    continue;
    }
  }
  return 0;
}
@group(0) @binding(0) var<storage, read_write> alphacov_step_outb_buf : array<i32>;
struct U_alphacov_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_alphacov_step : U_alphacov_step;
@compute @workgroup_size(64)
fn alphacov_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_alphacov_step.frame;
  let px = (gid - ((gid / ac_width) * ac_width));
  let py = (gid / ac_width);
  let tcx = (px / 34);
  let tcy = (py / 34);
  let hue = ((tcx * 3) + (tcy * 5));
  let hm = (hue - ((hue / 6) * 6));
  let fr = select(select(select(select(select(80, 250, (hm == 4)), 120, (hm == 3)), 250, (hm == 2)), 90, (hm == 1)), 240, (hm == 0));
  let fg = select(select(select(select(select(200, 210, (hm == 4)), 200, (hm == 3)), 90, (hm == 2)), 220, (hm == 1)), 120, (hm == 0));
  let fb = select(select(select(select(select(240, 90, (hm == 4)), 240, (hm == 3)), 200, (hm == 2)), 120, (hm == 1)), 70, (hm == 0));
  let cov256 = select((ac_super(px, py, 0, 0) * 16), (ac_in(px, py) * 256), (px < ac_half_w));
  let bgr = (20 + (py / 24));
  let bgb = (40 + (px / 24));
  let ored = (((fr * cov256) + (bgr * (256 - cov256))) / 256);
  let ogreen = (((fg * cov256) + (24 * (256 - cov256))) / 256);
  let oblue = (((fb * cov256) + (bgb * (256 - cov256))) / 256);
  alphacov_step_outb_buf[gid] = (((ored * 65536) + (ogreen * 256)) + oblue);
}