// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const bs_width : i32 = 1024;
const bs_half_w : i32 = 512;
const bs_half_h : i32 = 384;
fn bs_fall(px : i32, py : i32, cx : i32, cy : i32) -> f32 {
  let dx = f32(f32((px - cx)));
  let dy = f32(f32((py - cy)));
  let d2 = ((dx * dx) + (dy * dy));
  let inten = max(0.0, (0x1.000000p+0f - (d2 / 0x1.068000p+12f)));
  return ((inten * inten) * inten);
}
@group(0) @binding(0) var<storage, read_write> bloom_scene_step_outb_buf : array<i32>;
struct U_bloom_scene_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_bloom_scene_step : U_bloom_scene_step;
@compute @workgroup_size(64)
fn bloom_scene_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_bloom_scene_step.frame;
  let px = (gid - ((gid / bs_width) * bs_width));
  let py = (gid / bs_width);
  let f = (f32(f32(frame)) / 0x1.000000p+5f);
  let x0 = (bs_half_w + i32((cos(f) * 0x1.2c0000p+8f)));
  let y0 = (bs_half_h + i32((sin(f) * 0x1.5e0000p+7f)));
  let x1 = (bs_half_w + i32((cos(((f * 0x1.4cccccp+0f) + 0x1.0cccccp+1f)) * 0x1.e00000p+7f)));
  let y1 = (bs_half_h + i32((sin(((f * 0x1.4cccccp+0f) + 0x1.0cccccp+1f)) * 0x1.f40000p+7f)));
  let x2 = (bs_half_w + i32((cos(((f * 0x1.999998p-1f) + 0x1.0cccccp+2f)) * 0x1.4a0000p+8f)));
  let y2 = (bs_half_h + i32((sin(((f * 0x1.999998p-1f) + 0x1.0cccccp+2f)) * 0x1.2c0000p+7f)));
  let a = bs_fall(px, py, x0, y0);
  let b = bs_fall(px, py, x1, y1);
  let c = bs_fall(px, py, x2, y2);
  let r = (((a * 0x1.fe0000p+7f) + (b * 0x1.180000p+6f)) + (c * 0x1.680000p+6f));
  let g = (((a * 0x1.180000p+6f) + (b * 0x1.fe0000p+7f)) + (c * 0x1.b80000p+6f));
  let bl = (((a * 0x1.e00000p+5f) + (b * 0x1.e00000p+6f)) + (c * 0x1.fe0000p+7f));
  let ri = i32(min(0x1.fe0000p+7f, (r + 0x1.800000p+2f)));
  let gi = i32(min(0x1.fe0000p+7f, (g + 0x1.c00000p+2f)));
  let bi = i32(min(0x1.fe0000p+7f, (bl + 0x1.600000p+3f)));
  bloom_scene_step_outb_buf[gid] = (((ri * 65536) + (gi * 256)) + bi);
}