// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const bl_width : i32 = 1024;
const bl_taps : i32 = 40;
fn bl_clamp(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
fn bl_extract(texel : i32, ch : i32) -> i32 {
  if ((ch == 0)) {
  return (texel / 65536);
  } else {
  if ((ch == 1)) {
  return ((texel / 256) - ((texel / 65536) * 256));
  } else {
  return (texel - ((texel / 256) * 256));
  }
  }
}
fn bl_glow(px__a : i32, py__a : i32, ch__a : i32, k__a : i32, acc__a : i32) -> i32 {
  var px = px__a;
  var py = py__a;
  var ch = ch__a;
  var k = k__a;
  var acc = acc__a;
  loop {
    if ((k >= bl_taps)) {
    return acc;
    } else {
    let ang = (f32(f32(k)) * 0x1.33126ep+1f);
    let rad = (sqrt(f32(f32(k))) * 0x1.b33332p+1f);
    let dx = i32((cos(ang) * rad));
    let dy = i32((sin(ang) * rad));
    let sx = bl_clamp((px + dx), 0, 1023);
    let sy = bl_clamp((py + dy), 0, 767);
    let idx = ((sy * 1024) + sx);
    let texel = bloom_step_scenebuf_buf[idx];
    let c = bl_extract(texel, ch);
    let bright = select(0, (c - 150), (c > 150));
    let _mv1 = px;
    let _mv2 = py;
    let _mv3 = ch;
    let _mv4 = (k + 1);
    let _mv5 = (acc + bright);
    px = _mv1;
    py = _mv2;
    ch = _mv3;
    k = _mv4;
    acc = _mv5;
    continue;
    }
  }
  return 0;
}
@group(0) @binding(0) var<storage, read_write> bloom_step_scenebuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> bloom_step_outb_buf : array<i32>;
struct U_bloom_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_bloom_step : U_bloom_step;
@compute @workgroup_size(64)
fn bloom_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_bloom_step.frame;
  let px = (gid - ((gid / bl_width) * bl_width));
  let py = (gid / bl_width);
  let base = bloom_step_scenebuf_buf[gid];
  let gr = bl_glow(px, py, 0, 0, 0);
  let gg = bl_glow(px, py, 1, 0, 0);
  let gb = bl_glow(px, py, 2, 0, 0);
  let br = (base / 65536);
  let bg = ((base / 256) - ((base / 65536) * 256));
  let bb = (base - ((base / 256) * 256));
  let fr = bl_clamp((br + (gr / 34)), 0, 255);
  let fg = bl_clamp((bg + (gg / 34)), 0, 255);
  let fb = bl_clamp((bb + (gb / 34)), 0, 255);
  bloom_step_outb_buf[gid] = (((fr * 65536) + (fg * 256)) + fb);
}