// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const cu_width : i32 = 1024;
const cu_half_w : i32 = 512;
const cu_half_h : i32 = 384;
fn cu_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn cu_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((cu_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((cu_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((cu_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn cu_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / 0x1.800000p+9f);
  return cu_pack((0x1.47ae14p-5f + (h * 0x1.999998p-5f)), (0x1.999998p-5f + (h * 0x1.47ae14p-4f)), (0x1.70a3d6p-4f + (h * 0x1.47ae14p-3f)));
}
fn cu_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / cu_width) * cu_width));
  let py = (gid / cu_width);
  let fx = (f32(f32((px - cu_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((cu_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.47ae14p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.999998p+0f / rl);
  let ay = (f32(f32(frame)) / 0x1.100000p+5f);
  let ax = (f32(f32(frame)) / 0x1.980000p+5f);
  let cy = cos(ay);
  let sy = sin(ay);
  let cx = cos(ax);
  let sx = sin(ax);
  let oz0 = (0.0 - 0x1.b33332p+1f);
  let oxa = (oz0 * sy);
  let oza = (oz0 * cy);
  let oxb = oxa;
  let oyb = (oza * sx);
  let ozb = (oza * cx);
  let dxa = ((dx * cy) + (dz * sy));
  let dza = ((0.0 - (dx * sy)) + (dz * cy));
  let dxb = dxa;
  let dyb = ((dy * cx) + (dza * sx));
  let dzb = ((0.0 - (dy * sx)) + (dza * cx));
  let t1x = (((0.0 - 0x1.000000p+0f) - oxb) / dxb);
  let t2x = ((0x1.000000p+0f - oxb) / dxb);
  let nxr = min(t1x, t2x);
  let fxr = max(t1x, t2x);
  let t1y = (((0.0 - 0x1.000000p+0f) - oyb) / dyb);
  let t2y = ((0x1.000000p+0f - oyb) / dyb);
  let nyr = min(t1y, t2y);
  let fyr = max(t1y, t2y);
  let t1z = (((0.0 - 0x1.000000p+0f) - ozb) / dzb);
  let t2z = ((0x1.000000p+0f - ozb) / dzb);
  let nzr = min(t1z, t2z);
  let fzr = max(t1z, t2z);
  let tmin = max(nxr, max(nyr, nzr));
  let tmax = min(fxr, min(fyr, fzr));
  if ((tmin > tmax)) {
  return cu_bg(py);
  } else {
  if ((tmax < 0x1.0624dcp-10f)) {
  return cu_bg(py);
  } else {
  let nlx = select(0.0, select(0x1.000000p+0f, (0.0 - 0x1.000000p+0f), (dxb > 0.0)), ((nxr >= nyr) && (nxr >= nzr)));
  let nly = select(0.0, select(0x1.000000p+0f, (0.0 - 0x1.000000p+0f), (dyb > 0.0)), ((nyr >= nxr) && (nyr >= nzr)));
  let nlz = select(0.0, select(0x1.000000p+0f, (0.0 - 0x1.000000p+0f), (dzb > 0.0)), ((nzr >= nxr) && (nzr >= nyr)));
  let br = select(select(select(select(select(0x1.ccccccp-1f, 0x1.000000p-2f, (nlz > 0x1.000000p-1f)), 0x1.333332p-2f, (nly < (0.0 - 0x1.000000p-1f))), 0x1.666666p-2f, (nly > 0x1.000000p-1f)), 0x1.b33332p-1f, (nlx < (0.0 - 0x1.000000p-1f))), 0x1.e66666p-1f, (nlx > 0x1.000000p-1f));
  let bg = select(select(select(select(select(0x1.999998p-1f, 0x1.199998p-1f, (nlz > 0x1.000000p-1f)), 0x1.199998p-1f, (nly < (0.0 - 0x1.000000p-1f))), 0x1.b33332p-1f, (nly > 0x1.000000p-1f)), 0x1.800000p-1f, (nlx < (0.0 - 0x1.000000p-1f))), 0x1.666666p-2f, (nlx > 0x1.000000p-1f));
  let bb = select(select(select(select(select(0x1.333332p-2f, 0x1.ccccccp-1f, (nlz > 0x1.000000p-1f)), 0x1.b33332p-1f, (nly < (0.0 - 0x1.000000p-1f))), 0x1.ccccccp-2f, (nly > 0x1.000000p-1f)), 0x1.666666p-2f, (nlx < (0.0 - 0x1.000000p-1f))), 0x1.333332p-2f, (nlx > 0x1.000000p-1f));
  let lx = 0x1.999998p-2f;
  let ly = 0x1.70a3d6p-1f;
  let lz = (0.0 - 0x1.1eb850p-1f);
  let ndl = max(0.0, (((nlx * lx) + (nly * ly)) + (nlz * lz)));
  let sh = (0x1.000000p-2f + (ndl * 0x1.b33332p-1f));
  return cu_pack((br * sh), (bg * sh), (bb * sh));
  }
  }
}
@group(0) @binding(0) var<storage, read_write> cube_step_outb_buf : array<i32>;
struct U_cube_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_cube_step : U_cube_step;
@compute @workgroup_size(64)
fn cube_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_cube_step.frame;
  cube_step_outb_buf[gid] = cu_render(gid, frame);
}