// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const cm_width : i32 = 1024;
const cm_half_w : i32 = 512;
const cm_half_h : i32 = 384;
fn cm_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn cm_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((cm_clamp01(r) * 0x1.fe0000p+7f)) * 65536) + (i32((cm_clamp01(g) * 0x1.fe0000p+7f)) * 256)) + i32((cm_clamp01(b) * 0x1.fe0000p+7f)));
}
fn cm_noise(x : f32, z : f32) -> f32 {
  return (((sin((x * 0x1.ccccccp-1f)) * cos((z * 0x1.999998p-1f))) + ((sin(((x * 0x1.e66666p+0f) + 0x1.4cccccp+0f)) * cos((z * 0x1.0cccccp+1f))) * 0x1.000000p-1f)) + (sin(((x * 0x1.a66666p+1f) - (z * 0x1.666666p+0f))) * 0x1.000000p-2f));
}
fn cm_cloud(dx : f32, dz : f32, dy : f32, frame : i32) -> f32 {
  let t = (0x1.4cccccp+0f / dy);
  let cx = (((dx * t) * 0x1.666666p+0f) + (f32(f32(frame)) / 0x1.500000p+5f));
  let cz = ((dz * t) * 0x1.666666p+0f);
  let n = cm_noise(cx, cz);
  return (cm_clamp01(((n - 0x1.eb851ep-4f) * 0x1.4cccccp+0f)) * cm_clamp01((dy * 0x1.400000p+2f)));
}
fn cm_sun(d : f32) -> f32 {
  if ((d <= 0.0)) {
  return 0.0;
  } else {
  let d2 = (d * d);
  let d4 = (d2 * d2);
  return (((d4 * d4) * d4) * d2);
  }
}
fn cm_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / cm_width) * cm_width));
  let py = (gid / cm_width);
  let fx = (f32(f32((px - cm_half_w))) / 0x1.000000p+9f);
  let fy = (f32(f32((cm_half_h - py))) / 0x1.800000p+8f);
  let yaw = (f32(f32(frame)) / 0x1.e00000p+5f);
  let ca = cos(yaw);
  let sa = sin(yaw);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+0f));
  let dx0 = (fx / rl);
  let dy = (fy / rl);
  let dz0 = (0x1.000000p+0f / rl);
  let dx = ((dx0 * ca) + (dz0 * sa));
  let dz = ((0.0 - (dx0 * sa)) + (dz0 * ca));
  let sund = (((dx * 0x1.ae147ap-2f) + (dy * 0x1.5c28f4p-2f)) - (dz * 0x1.ae147ap-1f));
  let glow = (cm_sun(sund) * 0x1.666666p-1f);
  let disk = select(0.0, 0x1.999998p+0f, (sund > 0x1.fe353ep-1f));
  if ((dy < (0.0 - 0x1.47ae14p-6f))) {
  return cm_pack((0x1.999998p-4f - (dy * 0x1.999998p-5f)), (0x1.70a3d6p-4f - (dy * 0x1.47ae14p-5f)), 0x1.47ae14p-4f);
  } else {
  let cloudv = select(0.0, cm_cloud(dx, dz, dy, frame), (dy > 0x1.eb851ep-6f));
  let base_r = (0x1.333332p-2f + (dy * 0x1.999998p-4f));
  let base_g = (0x1.000000p-1f + (dy * 0x1.333332p-2f));
  let base_b = (0x1.a3d70ap-1f + (dy * 0x1.333332p-3f));
  let skr = ((base_r + (glow * 0x1.ccccccp-1f)) + disk);
  let skg = ((base_g + (glow * 0x1.8f5c28p-1f)) + disk);
  let skb = ((base_b + (glow * 0x1.ccccccp-2f)) + disk);
  return cm_pack(((skr * (0x1.000000p+0f - cloudv)) + cloudv), ((skg * (0x1.000000p+0f - cloudv)) + cloudv), ((skb * (0x1.000000p+0f - cloudv)) + cloudv));
  }
}
@group(0) @binding(0) var<storage, read_write> cubemap_step_outb_buf : array<i32>;
struct U_cubemap_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_cubemap_step : U_cubemap_step;
@compute @workgroup_size(64)
fn cubemap_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_cubemap_step.frame;
  cubemap_step_outb_buf[gid] = cm_render(gid, frame);
}