// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const d2_width : i32 = 1024;
const d2_half_w : i32 = 512;
const d2_half_h : i32 = 384;
const d2_tris : i32 = 20;
fn d2_mt(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, v0x : f32, v0y : f32, v0z : f32, v1x : f32, v1y : f32, v1z : f32, v2x : f32, v2y : f32, v2z : f32) -> f32 {
  let e1x = (v1x - v0x);
  let e1y = (v1y - v0y);
  let e1z = (v1z - v0z);
  let e2x = (v2x - v0x);
  let e2y = (v2y - v0y);
  let e2z = (v2z - v0z);
  let pvx = ((dy * e2z) - (dz * e2y));
  let pvy = ((dz * e2x) - (dx * e2z));
  let pvz = ((dx * e2y) - (dy * e2x));
  let det = (((e1x * pvx) + (e1y * pvy)) + (e1z * pvz));
  let adet = select(det, (0.0 - det), (det < 0.0));
  if ((adet < 0x1.4f8b58p-17f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let inv = (0x1.000000p+0f / det);
  let tvx = (ox - v0x);
  let tvy = (oy - v0y);
  let tvz = (oz - v0z);
  let u = ((((tvx * pvx) + (tvy * pvy)) + (tvz * pvz)) * inv);
  if ((u < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if ((u > 0x1.000000p+0f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let qvx = ((tvy * e1z) - (tvz * e1y));
  let qvy = ((tvz * e1x) - (tvx * e1z));
  let qvz = ((tvx * e1y) - (tvy * e1x));
  let vv = ((((dx * qvx) + (dy * qvy)) + (dz * qvz)) * inv);
  if ((vv < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if (((u + vv) > 0x1.000000p+0f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((((e2x * qvx) + (e2y * qvy)) + (e2z * qvz)) * inv);
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
  }
  }
  }
  }
}
fn d2_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= d2_tris)) {
    return best_id;
    } else {
    let a0 = d20_step_meshbuf_buf[(i * 9)];
    let a1 = d20_step_meshbuf_buf[((i * 9) + 1)];
    let a2 = d20_step_meshbuf_buf[((i * 9) + 2)];
    let b0 = d20_step_meshbuf_buf[((i * 9) + 3)];
    let b1 = d20_step_meshbuf_buf[((i * 9) + 4)];
    let b2 = d20_step_meshbuf_buf[((i * 9) + 5)];
    let c0 = d20_step_meshbuf_buf[((i * 9) + 6)];
    let c1 = d20_step_meshbuf_buf[((i * 9) + 7)];
    let c2 = d20_step_meshbuf_buf[((i * 9) + 8)];
    let t = d2_mt(ox, oy, oz, dx, dy, dz, (f32(f32(a0)) / 0x1.000000p+10f), (f32(f32(a1)) / 0x1.000000p+10f), (f32(f32(a2)) / 0x1.000000p+10f), (f32(f32(b0)) / 0x1.000000p+10f), (f32(f32(b1)) / 0x1.000000p+10f), (f32(f32(b2)) / 0x1.000000p+10f), (f32(f32(c0)) / 0x1.000000p+10f), (f32(f32(c1)) / 0x1.000000p+10f), (f32(f32(c2)) / 0x1.000000p+10f));
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    let nid = select(best_id, i, (take == 1));
    let nt = select(best_t, t, (take == 1));
    let _mv1 = ox;
    let _mv2 = oy;
    let _mv3 = oz;
    let _mv4 = dx;
    let _mv5 = dy;
    let _mv6 = dz;
    let _mv7 = (i + 1);
    let _mv8 = nid;
    let _mv9 = nt;
    ox = _mv1;
    oy = _mv2;
    oz = _mv3;
    dx = _mv4;
    dy = _mv5;
    dz = _mv6;
    i = _mv7;
    best_id = _mv8;
    best_t = _mv9;
    continue;
    }
  }
  return 0;
}
fn d2_glyph(d : i32) -> i32 {
  if ((d == 0)) {
  return 31599;
  } else {
  if ((d == 1)) {
  return 11415;
  } else {
  if ((d == 2)) {
  return 29671;
  } else {
  if ((d == 3)) {
  return 29647;
  } else {
  if ((d == 4)) {
  return 23497;
  } else {
  if ((d == 5)) {
  return 31183;
  } else {
  if ((d == 6)) {
  return 31215;
  } else {
  if ((d == 7)) {
  return 29266;
  } else {
  if ((d == 8)) {
  return 31727;
  } else {
  return 31695;
  }
  }
  }
  }
  }
  }
  }
  }
  }
}
fn d2_pow8(n : i32) -> i32 {
  if ((n <= 0)) {
  return 1;
  } else {
  if ((n == 1)) {
  return 8;
  } else {
  if ((n == 2)) {
  return 64;
  } else {
  if ((n == 3)) {
  return 512;
  } else {
  if ((n == 4)) {
  return 4096;
  } else {
  return 32768;
  }
  }
  }
  }
  }
}
fn d2_pow2(n : i32) -> i32 {
  if ((n <= 0)) {
  return 1;
  } else {
  if ((n == 1)) {
  return 2;
  } else {
  if ((n == 2)) {
  return 4;
  } else {
  return 8;
  }
  }
  }
}
fn d2_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn d2_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((d2_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((d2_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((d2_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn d2_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / 0x1.800000p+9f);
  return d2_pack((0x1.eb851ep-6f + (h * 0x1.47ae14p-5f)), (0x1.eb851ep-6f + (h * 0x1.999998p-5f)), (0x1.999998p-5f + (h * 0x1.70a3d6p-4f)));
}
fn d2_glyph_on(d : i32, col : i32, row : i32) -> i32 {
  if ((col < 0)) {
  return 0;
  } else {
  if ((col > 2)) {
  return 0;
  } else {
  if ((row < 0)) {
  return 0;
  } else {
  if ((row > 4)) {
  return 0;
  } else {
  let g = d2_glyph(d);
  let rowval = ((g / d2_pow8((4 - row))) - ((g / d2_pow8((5 - row))) * 8));
  let bit = ((rowval / d2_pow2((2 - col))) - ((rowval / d2_pow2((3 - col))) * 2));
  return bit;
  }
  }
  }
  }
}
fn d2_on_number(id : i32, qx : f32, qy : f32) -> i32 {
  let m = (id + 1);
  let nd = select(2, 1, (m < 10));
  let gw = 0x1.d70a3cp-4f;
  let tw = (f32(f32(nd)) * gw);
  let th = 0x1.ae147ap-3f;
  let tx = ((qx + (tw * 0x1.000000p-1f)) / tw);
  let ty = (((th * 0x1.000000p-1f) - qy) / th);
  if ((tx < 0.0)) {
  return 0;
  } else {
  if ((tx > 0x1.000000p+0f)) {
  return 0;
  } else {
  if ((ty < 0.0)) {
  return 0;
  } else {
  if ((ty > 0x1.000000p+0f)) {
  return 0;
  } else {
  let totalcols = (nd * 3);
  let gcol = i32((tx * f32(f32(totalcols))));
  let cell = (gcol / 3);
  let col = (gcol - (cell * 3));
  let row = i32((ty * 0x1.400000p+2f));
  let digit = select(select((m - ((m / 10) * 10)), (m / 10), (cell == 0)), m, (nd == 1));
  return d2_glyph_on(digit, col, row);
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> d20_step_meshbuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> d20_step_outb_buf : array<i32>;
struct U_d20_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_d20_step : U_d20_step;
@compute @workgroup_size(64)
fn d20_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_d20_step.frame;
  let px = (gid - ((gid / d2_width) * d2_width));
  let py = (gid / d2_width);
  let fx = (f32(f32((px - d2_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((d2_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.47ae14p+1f));
  let dx0 = (fx / rl);
  let dy0 = (fy / rl);
  let dz0 = (0x1.999998p+0f / rl);
  let ay = (f32(f32(frame)) / 0x1.700000p+5f);
  let ax = (f32(f32(frame)) / 0x1.1c0000p+6f);
  let cyv = cos(ay);
  let syv = sin(ay);
  let cxv = cos(ax);
  let sxv = sin(ax);
  let oz0 = (0.0 - 0x1.999998p+1f);
  let ox = (oz0 * syv);
  let oza = (oz0 * cyv);
  let oy = (oza * sxv);
  let oz = (oza * cxv);
  let dxa = ((dx0 * cyv) + (dz0 * syv));
  let dza = ((0.0 - (dx0 * syv)) + (dz0 * cyv));
  let dx = dxa;
  let dy = ((dy0 * cxv) + (dza * sxv));
  let dz = ((0.0 - (dy0 * sxv)) + (dza * cxv));
  let id = d2_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  let safe = select(id, 0, (id < 0));
  let a0 = d20_step_meshbuf_buf[(safe * 9)];
  let a1 = d20_step_meshbuf_buf[((safe * 9) + 1)];
  let a2 = d20_step_meshbuf_buf[((safe * 9) + 2)];
  let b0 = d20_step_meshbuf_buf[((safe * 9) + 3)];
  let b1 = d20_step_meshbuf_buf[((safe * 9) + 4)];
  let b2 = d20_step_meshbuf_buf[((safe * 9) + 5)];
  let c0 = d20_step_meshbuf_buf[((safe * 9) + 6)];
  let c1 = d20_step_meshbuf_buf[((safe * 9) + 7)];
  let c2 = d20_step_meshbuf_buf[((safe * 9) + 8)];
  let v0x = (f32(f32(a0)) / 0x1.000000p+10f);
  let v0y = (f32(f32(a1)) / 0x1.000000p+10f);
  let v0z = (f32(f32(a2)) / 0x1.000000p+10f);
  let v1x = (f32(f32(b0)) / 0x1.000000p+10f);
  let v1y = (f32(f32(b1)) / 0x1.000000p+10f);
  let v1z = (f32(f32(b2)) / 0x1.000000p+10f);
  let v2x = (f32(f32(c0)) / 0x1.000000p+10f);
  let v2y = (f32(f32(c1)) / 0x1.000000p+10f);
  let v2z = (f32(f32(c2)) / 0x1.000000p+10f);
  let e1x = (v1x - v0x);
  let e1y = (v1y - v0y);
  let e1z = (v1z - v0z);
  let e2x = (v2x - v0x);
  let e2y = (v2y - v0y);
  let e2z = (v2z - v0z);
  let nx0 = ((e1y * e2z) - (e1z * e2y));
  let ny0 = ((e1z * e2x) - (e1x * e2z));
  let nz0 = ((e1x * e2y) - (e1y * e2x));
  let nl = (sqrt((((nx0 * nx0) + (ny0 * ny0)) + (nz0 * nz0))) + 0x1.4f8b58p-17f);
  let nx = (nx0 / nl);
  let ny = (ny0 / nl);
  let nz = (nz0 / nl);
  let t = d2_mt(ox, oy, oz, dx, dy, dz, v0x, v0y, v0z, v1x, v1y, v1z, v2x, v2y, v2z);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let d00 = (((e1x * e1x) + (e1y * e1y)) + (e1z * e1z));
  let d01 = (((e1x * e2x) + (e1y * e2y)) + (e1z * e2z));
  let d11 = (((e2x * e2x) + (e2y * e2y)) + (e2z * e2z));
  let vpx = (hx - v0x);
  let vpy = (hy - v0y);
  let vpz = (hz - v0z);
  let d20 = (((vpx * e1x) + (vpy * e1y)) + (vpz * e1z));
  let d21 = (((vpx * e2x) + (vpy * e2y)) + (vpz * e2z));
  let denom = (((d00 * d11) - (d01 * d01)) + 0x1.4f8b58p-17f);
  let bv = (((d11 * d20) - (d01 * d21)) / denom);
  let bw = (((d00 * d21) - (d01 * d20)) / denom);
  let bu = ((0x1.000000p+0f - bv) - bw);
  let qx = ((bv * (0.0 - 0x1.147ae0p-1f)) + (bw * 0x1.147ae0p-1f));
  let qy = (((bu * 0x1.3d70a2p-1f) + (bv * (0.0 - 0x1.3d70a2p-2f))) + (bw * (0.0 - 0x1.3d70a2p-2f)));
  let onnum = d2_on_number(safe, qx, qy);
  let ndl = (((nx * 0x1.666666p-2f) + (ny * 0x1.70a3d6p-1f)) + (nz * (0.0 - 0x1.333332p-1f)));
  let lit = (0x1.eb851ep-3f + (select(ndl, (0.0 - ndl), (ndl < 0.0)) * 0x1.a3d70ap-1f));
  let facer = (0x1.70a3d6p-1f * lit);
  let faceg = (0x1.999998p-4f * lit);
  let faceb = (0x1.eb851ep-4f * lit);
  let numv = (0x1.199998p-1f + (lit * 0x1.000000p-1f));
  let out = select(select(d2_pack(facer, faceg, faceb), d2_pack(numv, numv, numv), (onnum == 1)), d2_bg(py), (id < 0));
  d20_step_outb_buf[gid] = out;
}