// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const de_width : i32 = 1024;
const de_half_w : i32 = 512;
const de_half_h : i32 = 384;
const de_lights : i32 = 20;
const de_miss : i32 = 8000000;
fn de_lr(k : i32) -> f32 {
  let m = (k - ((k / 6) * 6));
  if ((m == 0)) {
  return 0x1.000000p+0f;
  } else {
  if ((m == 1)) {
  return 0x1.333332p-2f;
  } else {
  if ((m == 2)) {
  return 0x1.666666p-2f;
  } else {
  if ((m == 3)) {
  return 0x1.000000p+0f;
  } else {
  if ((m == 4)) {
  return 0x1.ccccccp-1f;
  } else {
  return 0x1.999998p-2f;
  }
  }
  }
  }
  }
}
fn de_lg(k : i32) -> f32 {
  let m = (k - ((k / 6) * 6));
  if ((m == 0)) {
  return 0x1.999998p-2f;
  } else {
  if ((m == 1)) {
  return 0x1.000000p-1f;
  } else {
  if ((m == 2)) {
  return 0x1.b33332p-1f;
  } else {
  if ((m == 3)) {
  return 0x1.b33332p-1f;
  } else {
  if ((m == 4)) {
  return 0x1.666666p-2f;
  } else {
  return 0x1.ccccccp-1f;
  }
  }
  }
  }
  }
}
fn de_lb(k : i32) -> f32 {
  let m = (k - ((k / 6) * 6));
  if ((m == 0)) {
  return 0x1.333332p-2f;
  } else {
  if ((m == 1)) {
  return 0x1.000000p+0f;
  } else {
  if ((m == 2)) {
  return 0x1.333332p-1f;
  } else {
  if ((m == 3)) {
  return 0x1.333332p-2f;
  } else {
  if ((m == 4)) {
  return 0x1.ccccccp-1f;
  } else {
  return 0x1.ccccccp-1f;
  }
  }
  }
  }
  }
}
fn de_accum(posx__a : f32, posy__a : f32, posz__a : f32, nx__a : f32, ny__a : f32, nz__a : f32, frame__a : f32, ch__a : i32, k__a : i32, acc__a : i32) -> i32 {
  var posx = posx__a;
  var posy = posy__a;
  var posz = posz__a;
  var nx = nx__a;
  var ny = ny__a;
  var nz = nz__a;
  var frame = frame__a;
  var ch = ch__a;
  var k = k__a;
  var acc = acc__a;
  loop {
    if ((k >= de_lights)) {
    return acc;
    } else {
    let la = ((f32(f32(k)) * 0x1.3d70a2p-1f) + frame);
    let lx = (cos(la) * 0x1.599998p+1f);
    let ly = (sin((la * 0x1.333332p-1f)) * 0x1.999998p+0f);
    let lz = ((sin(la) * 0x1.599998p+1f) - 0x1.999998p-2f);
    let ddx = (lx - posx);
    let ddy = (ly - posy);
    let ddz = (lz - posz);
    let d2 = (((ddx * ddx) + (ddy * ddy)) + (ddz * ddz));
    let dist = (sqrt(d2) + 0x1.0624dcp-10f);
    let ndl = (max(0.0, (((nx * ddx) + (ny * ddy)) + (nz * ddz))) / dist);
    let atten = (0x1.0cccccp+2f / (0x1.000000p-1f + d2));
    let lc = select(select(de_lb(k), de_lg(k), (ch == 1)), de_lr(k), (ch == 0));
    let _mv0 = posx;
    let _mv1 = posy;
    let _mv2 = posz;
    let _mv3 = nx;
    let _mv4 = ny;
    let _mv5 = nz;
    let _mv6 = frame;
    let _mv7 = ch;
    let _mv8 = (k + 1);
    let _mv9 = (acc + i32((((ndl * atten) * lc) * 0x1.2c0000p+8f)));
    posx = _mv0;
    posy = _mv1;
    posz = _mv2;
    nx = _mv3;
    ny = _mv4;
    nz = _mv5;
    frame = _mv6;
    ch = _mv7;
    k = _mv8;
    acc = _mv9;
    continue;
    }
  }
  return 0;
}
fn de_clamp(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
@group(0) @binding(0) var<storage, read_write> deferred_step_galb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> deferred_step_gnrm_buf : array<i32>;
@group(0) @binding(2) var<storage, read_write> deferred_step_gdep_buf : array<i32>;
@group(0) @binding(3) var<storage, read_write> deferred_step_outb_buf : array<i32>;
struct U_deferred_step {
  frame : i32,
}
@group(0) @binding(4) var<uniform> u_deferred_step : U_deferred_step;
@compute @workgroup_size(64)
fn deferred_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_deferred_step.frame;
  let px = (gid - ((gid / de_width) * de_width));
  let py = (gid / de_width);
  let fx = (f32(f32((px - de_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((de_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.9eb850p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.ccccccp+0f / rl);
  let alb = deferred_step_galb_buf[gid];
  let nrm = deferred_step_gnrm_buf[gid];
  let dep = deferred_step_gdep_buf[gid];
  let t = (f32(f32(dep)) / 0x1.000000p+8f);
  let posx = (dx * t);
  let posy = (dy * t);
  let posz = ((0.0 - 0x1.400000p+2f) + (dz * t));
  let nx = ((f32(f32((nrm / 65536))) / 0x1.fc0000p+6f) - 0x1.000000p+0f);
  let ny = ((f32(f32(((nrm / 256) - ((nrm / 65536) * 256)))) / 0x1.fc0000p+6f) - 0x1.000000p+0f);
  let nz = ((f32(f32((nrm - ((nrm / 256) * 256)))) / 0x1.fc0000p+6f) - 0x1.000000p+0f);
  let ar = (alb / 65536);
  let ag = ((alb / 256) - ((alb / 65536) * 256));
  let ab = (alb - ((alb / 256) * 256));
  let lr = de_accum(posx, posy, posz, nx, ny, nz, (f32(f32(frame)) / 0x1.a00000p+4f), 0, 0, 0);
  let lg = de_accum(posx, posy, posz, nx, ny, nz, (f32(f32(frame)) / 0x1.a00000p+4f), 1, 0, 0);
  let lb = de_accum(posx, posy, posz, nx, ny, nz, (f32(f32(frame)) / 0x1.a00000p+4f), 2, 0, 0);
  let fr = de_clamp(((ar * (26 + lr)) / 255), 0, 255);
  let fg = de_clamp(((ag * (26 + lg)) / 255), 0, 255);
  let fb = de_clamp(((ab * (26 + lb)) / 255), 0, 255);
  let out = select((((fr * 65536) + (fg * 256)) + fb), ((20 * 256) + 30), (dep >= de_miss));
  deferred_step_outb_buf[gid] = out;
}