// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const gb_width : i32 = 1024;
const gb_half_w : i32 = 512;
const gb_half_h : i32 = 384;
const gb_count : i32 = 8;
const gb_miss : i32 = 8000000;
fn gb_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return 0x1.e66666p-1f;
  } else {
  if ((i == 2)) {
  return (0.0 - 0x1.b33332p-1f);
  } else {
  if ((i == 3)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 4)) {
  return (0.0 - 0x1.ccccccp-2f);
  } else {
  if ((i == 5)) {
  return 0x1.199998p-1f;
  } else {
  if ((i == 6)) {
  return (0.0 - 0x1.333332p-1f);
  } else {
  return 0x1.333332p-3f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 2)) {
  return 0x1.000000p-2f;
  } else {
  if ((i == 3)) {
  return (0.0 - 0x1.999998p-1f);
  } else {
  if ((i == 4)) {
  return (0.0 - 0x1.333332p-1f);
  } else {
  if ((i == 5)) {
  return 0x1.800000p-1f;
  } else {
  if ((i == 6)) {
  return 0x1.666666p-1f;
  } else {
  return 0x1.999998p-4f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.999998p-3f);
  } else {
  if ((i == 2)) {
  return 0x1.999998p-4f;
  } else {
  if ((i == 3)) {
  return 0x1.999998p-3f;
  } else {
  if ((i == 4)) {
  return (0.0 - 0x1.333332p-2f);
  } else {
  if ((i == 5)) {
  return 0x1.333332p-2f;
  } else {
  if ((i == 6)) {
  return (0.0 - 0x1.999998p-4f);
  } else {
  return 0x1.999998p-1f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 1)) {
  return 0x1.3d70a2p-1f;
  } else {
  if ((i == 2)) {
  return 0x1.333332p-1f;
  } else {
  if ((i == 3)) {
  return 0x1.199998p-1f;
  } else {
  if ((i == 4)) {
  return 0x1.000000p-1f;
  } else {
  if ((i == 5)) {
  return 0x1.000000p-1f;
  } else {
  if ((i == 6)) {
  return 0x1.d70a3cp-2f;
  } else {
  return 0x1.000000p-1f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cr(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.b33332p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 2)) {
  return 0x1.000000p-2f;
  } else {
  if ((i == 3)) {
  return 0x1.666666p-1f;
  } else {
  if ((i == 4)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 5)) {
  return 0x1.333332p-2f;
  } else {
  if ((i == 6)) {
  return 0x1.e66666p-1f;
  } else {
  return 0x1.ccccccp-1f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cg(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.800000p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.333332p-2f;
  } else {
  if ((i == 2)) {
  return 0x1.999998p-1f;
  } else {
  if ((i == 3)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 4)) {
  return 0x1.999998p-1f;
  } else {
  if ((i == 5)) {
  return 0x1.ccccccp-2f;
  } else {
  if ((i == 6)) {
  return 0x1.199998p-1f;
  } else {
  return 0x1.ccccccp-2f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cb(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.ccccccp-2f;
  } else {
  if ((i == 1)) {
  return 0x1.1eb850p-2f;
  } else {
  if ((i == 2)) {
  return 0x1.800000p-1f;
  } else {
  if ((i == 3)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 4)) {
  return 0x1.999998p-2f;
  } else {
  if ((i == 5)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 6)) {
  return 0x1.333332p-2f;
  } else {
  return 0x1.4cccccp-1f;
  }
  }
  }
  }
  }
  }
  }
}
fn gb_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - gb_cx(i));
  let ly = (oy - gb_cy(i));
  let lz = (oz - gb_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = gb_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn gb_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= gb_count)) {
    return best_id;
    } else {
    let t = gb_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn gb_nbyte(n : f32) -> i32 {
  return i32(((n + 0x1.000000p+0f) * 0x1.fc0000p+6f));
}
@group(0) @binding(0) var<storage, read_write> gbuf_step_galb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> gbuf_step_gnrm_buf : array<i32>;
@group(0) @binding(2) var<storage, read_write> gbuf_step_gdep_buf : array<i32>;
@compute @workgroup_size(64)
fn gbuf_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let px = (gid - ((gid / gb_width) * gb_width));
  let py = (gid / gb_width);
  let fx = (f32(f32((px - gb_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((gb_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.9eb850p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.ccccccp+0f / rl);
  let ox = 0.0;
  let oy = 0.0;
  let oz = (0.0 - 0x1.400000p+2f);
  let id = gb_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  let t = select(gb_hit(ox, oy, oz, dx, dy, dz, id), 0.0, (id < 0));
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - gb_cx(id)) / gb_rad(id)), 0.0, (id < 0));
  let ny = select(((hy - gb_cy(id)) / gb_rad(id)), 0x1.000000p+0f, (id < 0));
  let nz = select(((hz - gb_cz(id)) / gb_rad(id)), 0.0, (id < 0));
  let albv = select((((i32((gb_cr(id) * 0x1.fe0000p+7f)) * 65536) + (i32((gb_cg(id) * 0x1.fe0000p+7f)) * 256)) + i32((gb_cb(id) * 0x1.fe0000p+7f))), 0, (id < 0));
  let nrmv = (((gb_nbyte(nx) * 65536) + (gb_nbyte(ny) * 256)) + gb_nbyte(nz));
  let depv = select(i32((t * 0x1.000000p+8f)), gb_miss, (id < 0));
  gbuf_step_galb_buf[gid] = albv;
  gbuf_step_gnrm_buf[gid] = nrmv;
  gbuf_step_gdep_buf[gid] = depv;
}