// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const gl_width : i32 = 1024;
const gl_half_w : i32 = 512;
const gl_half_h : i32 = 384;
const gl_tris : i32 = 20;
fn gl_mt(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, v0x : f32, v0y : f32, v0z : f32, v1x : f32, v1y : f32, v1z : f32, v2x : f32, v2y : f32, v2z : f32) -> f32 {
  let e1x = (v1x - v0x);
  let e1y = (v1y - v0y);
  let e1z = (v1z - v0z);
  let e2x = (v2x - v0x);
  let e2y = (v2y - v0y);
  let e2z = (v2z - v0z);
  let pvx = ((dy * e2z) - (dz * e2y));
  let pvy = ((dz * e2x) - (dx * e2z));
  let pvz = ((dx * e2y) - (dy * e2x));
  let det = (((e1x * pvx) + (e1y * pvy)) + (e1z * pvz));
  let adet = select(det, (0.0 - det), (det < 0.0));
  if ((adet < 0x1.4f8b58p-17f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let inv = (0x1.000000p+0f / det);
  let tvx = (ox - v0x);
  let tvy = (oy - v0y);
  let tvz = (oz - v0z);
  let u = ((((tvx * pvx) + (tvy * pvy)) + (tvz * pvz)) * inv);
  if ((u < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if ((u > 0x1.000000p+0f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let qvx = ((tvy * e1z) - (tvz * e1y));
  let qvy = ((tvz * e1x) - (tvx * e1z));
  let qvz = ((tvx * e1y) - (tvy * e1x));
  let vv = ((((dx * qvx) + (dy * qvy)) + (dz * qvz)) * inv);
  if ((vv < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if (((u + vv) > 0x1.000000p+0f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((((e2x * qvx) + (e2y * qvy)) + (e2z * qvz)) * inv);
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
  }
  }
  }
  }
}
fn gl_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= gl_tris)) {
    return best_id;
    } else {
    let a0 = gltf_step_meshbuf_buf[(i * 9)];
    let a1 = gltf_step_meshbuf_buf[((i * 9) + 1)];
    let a2 = gltf_step_meshbuf_buf[((i * 9) + 2)];
    let b0 = gltf_step_meshbuf_buf[((i * 9) + 3)];
    let b1 = gltf_step_meshbuf_buf[((i * 9) + 4)];
    let b2 = gltf_step_meshbuf_buf[((i * 9) + 5)];
    let c0 = gltf_step_meshbuf_buf[((i * 9) + 6)];
    let c1 = gltf_step_meshbuf_buf[((i * 9) + 7)];
    let c2 = gltf_step_meshbuf_buf[((i * 9) + 8)];
    let t = gl_mt(ox, oy, oz, dx, dy, dz, (f32(f32(a0)) / 0x1.000000p+10f), (f32(f32(a1)) / 0x1.000000p+10f), (f32(f32(a2)) / 0x1.000000p+10f), (f32(f32(b0)) / 0x1.000000p+10f), (f32(f32(b1)) / 0x1.000000p+10f), (f32(f32(b2)) / 0x1.000000p+10f), (f32(f32(c0)) / 0x1.000000p+10f), (f32(f32(c1)) / 0x1.000000p+10f), (f32(f32(c2)) / 0x1.000000p+10f));
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    let nid = select(best_id, i, (take == 1));
    let nt = select(best_t, t, (take == 1));
    let _mv1 = ox;
    let _mv2 = oy;
    let _mv3 = oz;
    let _mv4 = dx;
    let _mv5 = dy;
    let _mv6 = dz;
    let _mv7 = (i + 1);
    let _mv8 = nid;
    let _mv9 = nt;
    ox = _mv1;
    oy = _mv2;
    oz = _mv3;
    dx = _mv4;
    dy = _mv5;
    dz = _mv6;
    i = _mv7;
    best_id = _mv8;
    best_t = _mv9;
    continue;
    }
  }
  return 0;
}
fn gl_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn gl_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((gl_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((gl_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((gl_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn gl_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / 0x1.800000p+9f);
  return gl_pack((0x1.47ae14p-5f + (h * 0x1.999998p-5f)), (0x1.999998p-5f + (h * 0x1.70a3d6p-4f)), (0x1.70a3d6p-4f + (h * 0x1.333332p-3f)));
}
fn gl_col_r(i : i32) -> f32 {
  return (0x1.ccccccp-2f + (f32(f32((i - ((i / 6) * 6)))) * 0x1.70a3d6p-4f));
}
fn gl_col_g(i : i32) -> f32 {
  return (0x1.b33332p-1f - (f32(f32((i - ((i / 5) * 5)))) * 0x1.47ae14p-4f));
}
fn gl_col_b(i : i32) -> f32 {
  return (0x1.199998p-1f + (f32(f32((i - ((i / 4) * 4)))) * 0x1.999998p-4f));
}
@group(0) @binding(0) var<storage, read_write> gltf_step_meshbuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> gltf_step_outb_buf : array<i32>;
struct U_gltf_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_gltf_step : U_gltf_step;
@compute @workgroup_size(64)
fn gltf_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_gltf_step.frame;
  let px = (gid - ((gid / gl_width) * gl_width));
  let py = (gid / gl_width);
  let fx = (f32(f32((px - gl_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((gl_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.47ae14p+1f));
  let dx0 = (fx / rl);
  let dy0 = (fy / rl);
  let dz0 = (0x1.999998p+0f / rl);
  let ay = (f32(f32(frame)) / 0x1.300000p+5f);
  let ax = (f32(f32(frame)) / 0x1.c80000p+5f);
  let cy = cos(ay);
  let sy = sin(ay);
  let cx = cos(ax);
  let sx = sin(ax);
  let oz0 = (0.0 - 0x1.999998p+1f);
  let oxa = (oz0 * sy);
  let oza = (oz0 * cy);
  let ox = oxa;
  let oy = (oza * sx);
  let oz = (oza * cx);
  let dxa = ((dx0 * cy) + (dz0 * sy));
  let dza = ((0.0 - (dx0 * sy)) + (dz0 * cy));
  let dx = dxa;
  let dy = ((dy0 * cx) + (dza * sx));
  let dz = ((0.0 - (dy0 * sx)) + (dza * cx));
  let id = gl_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  let safe = select(id, 0, (id < 0));
  let a0 = gltf_step_meshbuf_buf[(safe * 9)];
  let a1 = gltf_step_meshbuf_buf[((safe * 9) + 1)];
  let a2 = gltf_step_meshbuf_buf[((safe * 9) + 2)];
  let b0 = gltf_step_meshbuf_buf[((safe * 9) + 3)];
  let b1 = gltf_step_meshbuf_buf[((safe * 9) + 4)];
  let b2 = gltf_step_meshbuf_buf[((safe * 9) + 5)];
  let c0 = gltf_step_meshbuf_buf[((safe * 9) + 6)];
  let c1 = gltf_step_meshbuf_buf[((safe * 9) + 7)];
  let c2 = gltf_step_meshbuf_buf[((safe * 9) + 8)];
  let v0x = (f32(f32(a0)) / 0x1.000000p+10f);
  let v0y = (f32(f32(a1)) / 0x1.000000p+10f);
  let v0z = (f32(f32(a2)) / 0x1.000000p+10f);
  let e1x = ((f32(f32(b0)) / 0x1.000000p+10f) - v0x);
  let e1y = ((f32(f32(b1)) / 0x1.000000p+10f) - v0y);
  let e1z = ((f32(f32(b2)) / 0x1.000000p+10f) - v0z);
  let e2x = ((f32(f32(c0)) / 0x1.000000p+10f) - v0x);
  let e2y = ((f32(f32(c1)) / 0x1.000000p+10f) - v0y);
  let e2z = ((f32(f32(c2)) / 0x1.000000p+10f) - v0z);
  let nx0 = ((e1y * e2z) - (e1z * e2y));
  let ny0 = ((e1z * e2x) - (e1x * e2z));
  let nz0 = ((e1x * e2y) - (e1y * e2x));
  let nl = (sqrt((((nx0 * nx0) + (ny0 * ny0)) + (nz0 * nz0))) + 0x1.4f8b58p-17f);
  let nx = (nx0 / nl);
  let ny = (ny0 / nl);
  let nz = (nz0 / nl);
  let ndl = (((nx * 0x1.666666p-2f) + (ny * 0x1.70a3d6p-1f)) + (nz * (0.0 - 0x1.333332p-1f)));
  let lit = (0x1.999998p-3f + (select(ndl, (0.0 - ndl), (ndl < 0.0)) * 0x1.b33332p-1f));
  let out = select(gl_pack((gl_col_r(id) * lit), (gl_col_g(id) * lit), (gl_col_b(id) * lit)), gl_bg(py), (id < 0));
  gltf_step_outb_buf[gid] = out;
}