// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const in_width : i32 = 1024;
const in_half_w : i32 = 512;
const in_half_h : i32 = 384;
const in_count : i32 = 25;
const in_cols : i32 = 5;
fn in_gx(i : i32) -> f32 {
  return (f32(f32(((i - ((i / in_cols) * in_cols)) - 2))) * 0x1.400000p+0f);
}
fn in_gz(i : i32) -> f32 {
  return (f32(f32(((i / in_cols) - 2))) * 0x1.400000p+0f);
}
const in_half : f32 = 0x1.ae147ap-2f;
fn in_col_r(i : i32) -> f32 {
  return (0x1.199998p-1f + (f32(f32((i - ((i / in_cols) * in_cols)))) * 0x1.70a3d6p-4f));
}
fn in_col_g(i : i32) -> f32 {
  return (0x1.ccccccp-2f + (f32(f32((i / in_cols))) * 0x1.999998p-4f));
}
fn in_col_b(i : i32) -> f32 {
  return (0x1.b33332p-1f - (f32(f32((i - ((i / in_cols) * in_cols)))) * 0x1.eb851ep-5f));
}
fn in_box_t(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32) -> f32 {
  let s = in_half;
  let t1x = (((0.0 - s) - ox) / dx);
  let t2x = ((s - ox) / dx);
  let nx = min(t1x, t2x);
  let fx = max(t1x, t2x);
  let t1y = (((0.0 - s) - oy) / dy);
  let t2y = ((s - oy) / dy);
  let ny = min(t1y, t2y);
  let fy = max(t1y, t2y);
  let t1z = (((0.0 - s) - oz) / dz);
  let t2z = ((s - oz) / dz);
  let nz = min(t1z, t2z);
  let fz = max(t1z, t2z);
  let tmin = max(nx, max(ny, nz));
  let tmax = min(fx, min(fy, fz));
  if ((tmin > tmax)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if ((tmax < 0x1.0624dcp-10f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  if ((tmin < 0x1.0624dcp-10f)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  return tmin;
  }
  }
  }
}
fn in_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  return in_box_t((ox - in_gx(i)), oy, (oz - in_gz(i)), dx, dy, dz);
}
fn in_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= in_count)) {
    return best_id;
    } else {
    let t = in_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn in_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn in_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((in_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((in_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((in_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn in_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / 0x1.800000p+9f);
  return in_pack((0x1.999998p-5f + (h * 0x1.eb851ep-5f)), (0x1.eb851ep-5f + (h * 0x1.70a3d6p-4f)), (0x1.999998p-4f + (h * 0x1.70a3d6p-3f)));
}
fn in_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / in_width) * in_width));
  let py = (gid / in_width);
  let fx = (f32(f32((px - in_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((in_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + ((fy - 0x1.666666p-2f) * (fy - 0x1.666666p-2f))) + 0x1.200000p+1f));
  let dx0 = (fx / rl);
  let dy0 = ((fy - 0x1.666666p-2f) / rl);
  let dz0 = (0x1.800000p+0f / rl);
  let ay = (f32(f32(frame)) / 0x1.400000p+5f);
  let cy = cos(ay);
  let sy = sin(ay);
  let ox0 = 0.0;
  let oy0 = 0x1.199998p+1f;
  let oz0 = (0.0 - 0x1.8cccccp+2f);
  let ox = ((ox0 * cy) + (oz0 * sy));
  let oz = ((0.0 - (ox0 * sy)) + (oz0 * cy));
  let dx = ((dx0 * cy) + (dz0 * sy));
  let dz = ((0.0 - (dx0 * sy)) + (dz0 * cy));
  let id = in_nearest(ox, oy0, oz, dx, dy0, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  return in_bg(py);
  } else {
  let lx = (ox - in_gx(id));
  let lz = (oz - in_gz(id));
  let t = in_box_t(lx, oy0, lz, dx, dy0, dz);
  let hx = (lx + (dx * t));
  let hy = (oy0 + (dy0 * t));
  let hz = (lz + (dz * t));
  let ax = select(hx, (0.0 - hx), (hx < 0.0));
  let aay = select(hy, (0.0 - hy), (hy < 0.0));
  let az = select(hz, (0.0 - hz), (hz < 0.0));
  let nlx = select(0.0, select((0.0 - 0x1.000000p+0f), 0x1.000000p+0f, (hx > 0.0)), ((ax >= aay) && (ax >= az)));
  let nly = select(0.0, select((0.0 - 0x1.000000p+0f), 0x1.000000p+0f, (hy > 0.0)), ((aay >= ax) && (aay >= az)));
  let nlz = select(0.0, select((0.0 - 0x1.000000p+0f), 0x1.000000p+0f, (hz > 0.0)), ((az >= ax) && (az >= aay)));
  let ndl = max(0.0, (((nlx * 0x1.999998p-2f) + (nly * 0x1.8f5c28p-1f)) + (nlz * (0.0 - 0x1.eb851ep-2f))));
  let sh = (0x1.c28f5cp-3f + (ndl * 0x1.c28f5cp-1f));
  return in_pack((in_col_r(id) * sh), (in_col_g(id) * sh), (in_col_b(id) * sh));
  }
}
@group(0) @binding(0) var<storage, read_write> instancing_step_outb_buf : array<i32>;
struct U_instancing_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_instancing_step : U_instancing_step;
@compute @workgroup_size(64)
fn instancing_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_instancing_step.frame;
  instancing_step_outb_buf[gid] = in_render(gid, frame);
}