// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const jl_width : i32 = 1024;
const jl_half_w : i32 = 512;
const jl_half_h : i32 = 384;
const jl_max : i32 = 128;
fn jl_mod(x : i32, m : i32) -> i32 {
  return (x - ((x / m) * m));
}
fn jl_iter(zr__a : f32, zi__a : f32, cr__a : f32, ci__a : f32, n__a : i32) -> i32 {
  var zr = zr__a;
  var zi = zi__a;
  var cr = cr__a;
  var ci = ci__a;
  var n = n__a;
  loop {
    if ((n >= jl_max)) {
    return jl_max;
    } else {
    if ((((zr * zr) + (zi * zi)) > 0x1.000000p+2f)) {
    return n;
    } else {
    let _mv0 = (((zr * zr) - (zi * zi)) + cr);
    let _mv1 = (((0x1.000000p+1f * zr) * zi) + ci);
    let _mv2 = cr;
    let _mv3 = ci;
    let _mv4 = (n + 1);
    zr = _mv0;
    zi = _mv1;
    cr = _mv2;
    ci = _mv3;
    n = _mv4;
    continue;
    }
    }
  }
  return 0;
}
fn jl_chan(it : i32, mul : i32, phase : i32) -> i32 {
  return jl_mod(((it * mul) + phase), 256);
}
fn jl_color(it : i32, frame : i32) -> i32 {
  if ((it >= jl_max)) {
  return 0;
  } else {
  let f = frame;
  let r = jl_chan(it, 8, (30 + f));
  let g = jl_chan(it, 5, (90 + f));
  let b = jl_chan(it, 11, (160 + f));
  return (((r * 65536) + (g * 256)) + b);
  }
}
fn jl_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / jl_width) * jl_width));
  let py = (gid / jl_width);
  let zr = (f32(f32((px - jl_half_w))) / 0x1.400000p+8f);
  let zi = (f32(f32((py - jl_half_h))) / 0x1.400000p+8f);
  let a = (f32(f32(frame)) / 0x1.400000p+5f);
  let cr = (0x1.93b644p-1f * cos(a));
  let ci = (0x1.93b644p-1f * sin(a));
  return jl_color(jl_iter(zr, zi, cr, ci, 0), frame);
}
@group(0) @binding(0) var<storage, read_write> julia_step_outb_buf : array<i32>;
struct U_julia_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_julia_step : U_julia_step;
@compute @workgroup_size(64)
fn julia_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_julia_step.frame;
  julia_step_outb_buf[gid] = jl_render(gid, frame);
}