// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const mb_width : i32 = 1024;
const mb_height : i32 = 768;
const mb_max : i32 = 96;
fn mb_mod(x : i32, m : i32) -> i32 {
  return (x - ((x / m) * m));
}
fn mb_iter(zr__a : i32, zi__a : i32, cr__a : i32, ci__a : i32, n__a : i32) -> i32 {
  var zr = zr__a;
  var zi = zi__a;
  var cr = cr__a;
  var ci = ci__a;
  var n = n__a;
  loop {
    if ((n >= mb_max)) {
    return mb_max;
    } else {
    if ((((zr * zr) + (zi * zi)) > 4000000)) {
    return n;
    } else {
    let _mv0 = ((((zr * zr) - (zi * zi)) / 1000) + cr);
    let _mv1 = ((((2 * zr) * zi) / 1000) + ci);
    let _mv2 = cr;
    let _mv3 = ci;
    let _mv4 = (n + 1);
    zr = _mv0;
    zi = _mv1;
    cr = _mv2;
    ci = _mv3;
    n = _mv4;
    continue;
    }
    }
  }
  return 0;
}
fn mb_cr(gid : i32) -> i32 {
  return (((mb_mod(gid, mb_width) * 3500) / mb_width) - 2500);
}
fn mb_ci(gid : i32) -> i32 {
  return ((((gid / mb_width) * 2400) / mb_height) - 1200);
}
fn mb_chan(it : i32, mul : i32, phase : i32) -> i32 {
  return mb_mod(((it * mul) + phase), 256);
}
fn mb_color(it : i32, frame : i32) -> i32 {
  if ((it >= mb_max)) {
  return 0;
  } else {
  let f = (frame * 2);
  let r = mb_chan(it, 9, f);
  let g = mb_chan(it, 6, (40 + f));
  let b = mb_chan(it, 13, (90 + f));
  return (((r * 65536) + (g * 256)) + b);
  }
}
@group(0) @binding(0) var<storage, read_write> mandel_step_outb_buf : array<i32>;
struct U_mandel_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_mandel_step : U_mandel_step;
@compute @workgroup_size(64)
fn mandel_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_mandel_step.frame;
  mandel_step_outb_buf[gid] = mb_color(mb_iter(0, 0, mb_cr(gid), mb_ci(gid), 0), frame);
}