// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const ms_width : i32 = 1024;
const ms_half_w : i32 = 512;
const ms_half_h : i32 = 384;
fn ms_ring(cx : f32, cy : f32, phase : f32) -> f32 {
  let r2 = ((cx * cx) + (cy * cy));
  if ((sin(((r2 * 0x1.d7dbf4p-11f) + phase)) > 0.0)) {
  return 0x1.000000p+0f;
  } else {
  return 0.0;
  }
}
fn ms_super(cx__a : f32, cy__a : f32, phase__a : f32, s__a : i32, acc__a : f32) -> f32 {
  var cx = cx__a;
  var cy = cy__a;
  var phase = phase__a;
  var s = s__a;
  var acc = acc__a;
  loop {
    if ((s >= 16)) {
    return acc;
    } else {
    let sxi = (s - ((s / 4) * 4));
    let syi = (s / 4);
    let ddx = ((f32(f32(sxi)) * 0x1.000000p-2f) - 0x1.800000p-2f);
    let ddy = ((f32(f32(syi)) * 0x1.000000p-2f) - 0x1.800000p-2f);
    let _mv0 = cx;
    let _mv1 = cy;
    let _mv2 = phase;
    let _mv3 = (s + 1);
    let _mv4 = (acc + ms_ring((cx + ddx), (cy + ddy), phase));
    cx = _mv0;
    cy = _mv1;
    phase = _mv2;
    s = _mv3;
    acc = _mv4;
    continue;
    }
  }
  return 0.0;
}
fn ms_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / ms_width) * ms_width));
  let py = (gid / ms_width);
  let cx = f32(f32((px - ms_half_w)));
  let cy = f32(f32((py - ms_half_h)));
  let phase = (f32(f32(frame)) / 0x1.400000p+4f);
  let v = select((ms_super(cx, cy, phase, 0, 0.0) / 0x1.000000p+4f), ms_ring(cx, cy, phase), (px < ms_half_w));
  let edge = select(0, 1, ((px > (ms_half_w - 2)) && (px < (ms_half_w + 2))));
  if ((edge == 1)) {
  return (((40 * 65536) + (90 * 256)) + 130);
  } else {
  let tint_r = select(0x1.199998p-1f, 0x1.800000p-1f, (px < ms_half_w));
  let tint_g = select(0x1.999998p-1f, 0x1.333332p-1f, (px < ms_half_w));
  let tint_b = 0x1.ccccccp-1f;
  let ir = i32(((v * tint_r) * 0x1.fe0000p+7f));
  let ig = i32(((v * tint_g) * 0x1.fe0000p+7f));
  let ib = i32(((v * tint_b) * 0x1.fe0000p+7f));
  return (((ir * 65536) + (ig * 256)) + ib);
  }
}
@group(0) @binding(0) var<storage, read_write> multisample_step_outb_buf : array<i32>;
struct U_multisample_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_multisample_step : U_multisample_step;
@compute @workgroup_size(64)
fn multisample_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_multisample_step.frame;
  multisample_step_outb_buf[gid] = ms_render(gid, frame);
}