// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const nb_count : i32 = 1024;
const nb_width : i32 = 1024;
const nb_height : i32 = 768;
fn nb_fx(myx__a : i32, myy__a : i32, j__a : i32, acc__a : i32) -> i32 {
  var myx = myx__a;
  var myy = myy__a;
  var j = j__a;
  var acc = acc__a;
  loop {
    if ((j >= nb_count)) {
    return acc;
    } else {
    let jx = nbody_step_inb_buf[(j * 4)];
    let jy = nbody_step_inb_buf[((j * 4) + 1)];
    let dx = ((jx - myx) / 256);
    let dy = ((jy - myy) / 256);
    let d2 = (((dx * dx) + (dy * dy)) + 32);
    let w = (9000 / d2);
    let _mv1 = myx;
    let _mv2 = myy;
    let _mv3 = (j + 1);
    let _mv4 = (acc + (dx * w));
    myx = _mv1;
    myy = _mv2;
    j = _mv3;
    acc = _mv4;
    continue;
    }
  }
  return 0;
}
fn nb_fy(myx__a : i32, myy__a : i32, j__a : i32, acc__a : i32) -> i32 {
  var myx = myx__a;
  var myy = myy__a;
  var j = j__a;
  var acc = acc__a;
  loop {
    if ((j >= nb_count)) {
    return acc;
    } else {
    let jx = nbody_step_inb_buf[(j * 4)];
    let jy = nbody_step_inb_buf[((j * 4) + 1)];
    let dx = ((jx - myx) / 256);
    let dy = ((jy - myy) / 256);
    let d2 = (((dx * dx) + (dy * dy)) + 32);
    let w = (9000 / d2);
    let _mv1 = myx;
    let _mv2 = myy;
    let _mv3 = (j + 1);
    let _mv4 = (acc + (dy * w));
    myx = _mv1;
    myy = _mv2;
    j = _mv3;
    acc = _mv4;
    continue;
    }
  }
  return 0;
}
fn nb_wrap(v : i32, m : i32) -> i32 {
  let r = (v - ((v / m) * m));
  if ((r < 0)) {
  return (r + m);
  } else {
  return r;
  }
}
@group(0) @binding(0) var<storage, read_write> nbody_step_inb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> nbody_step_outb_buf : array<i32>;
struct U_nbody_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_nbody_step : U_nbody_step;
@compute @workgroup_size(64)
fn nbody_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_nbody_step.frame;
  let px = nbody_step_inb_buf[(gid * 4)];
  let py = nbody_step_inb_buf[((gid * 4) + 1)];
  let vx = nbody_step_inb_buf[((gid * 4) + 2)];
  let vy = nbody_step_inb_buf[((gid * 4) + 3)];
  let fx = nb_fx(px, py, 0, 0);
  let fy = nb_fy(px, py, 0, 0);
  let nvx = (vx + (fx / 32));
  let nvy = (vy + (fy / 32));
  let cvx = select(select(nvx, (0 - 4200), (nvx < (0 - 4200))), 4200, (nvx > 4200));
  let cvy = select(select(nvy, (0 - 4200), (nvy < (0 - 4200))), 4200, (nvy > 4200));
  let npx = nb_wrap((px + cvx), (nb_width * 256));
  let npy = nb_wrap((py + cvy), (nb_height * 256));
  nbody_step_outb_buf[(gid * 4)] = npx;
  nbody_step_outb_buf[((gid * 4) + 1)] = npy;
  nbody_step_outb_buf[((gid * 4) + 2)] = cvx;
  nbody_step_outb_buf[((gid * 4) + 3)] = cvy;
}