// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const oc_width : i32 = 1024;
const oc_half_w : i32 = 512;
const oc_half_h : i32 = 384;
const oc_count : i32 = 14;
fn oc_cx(i : i32) -> f32 {
  return (cos((f32(f32(i)) * 0x1.199998p+0f)) * (0x1.999998p-1f + f32(f32((i - ((i / 3) * 3))))));
}
fn oc_cy(i : i32) -> f32 {
  return (sin((f32(f32(i)) * 0x1.b33332p+0f)) * 0x1.4cccccp+0f);
}
fn oc_cz(i : i32) -> f32 {
  return (sin((f32(f32(i)) * 0x1.ccccccp-1f)) * 0x1.666666p+0f);
}
fn oc_enters(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, spin__a : f32, acc__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var spin = spin__a;
  var acc = acc__a;
  loop {
    if ((i >= oc_count)) {
    return acc;
    } else {
    let cx = ((oc_cx(i) * cos(spin)) - (oc_cz(i) * sin(spin)));
    let cz = ((oc_cx(i) * sin(spin)) + (oc_cz(i) * cos(spin)));
    let lx = (ox - cx);
    let ly = (oy - oc_cy(i));
    let lz = (oz - cz);
    let b = (((dx * lx) + (dy * ly)) + (dz * lz));
    let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - 0x1.47ae14p-1f);
    let disc = ((b * b) - c);
    let hit = select(0, select(0, 1, (((0.0 - b) + sqrt(disc)) > 0.0)), (disc > 0.0));
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = spin;
    let _mv8 = (acc + hit);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    spin = _mv7;
    acc = _mv8;
    continue;
    }
  }
  return 0;
}
fn oc_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((max(0.0, min(0x1.000000p+0f, r)) * 0x1.fe0000p+7f)) * 65536) + (i32((max(0.0, min(0x1.000000p+0f, g)) * 0x1.fe0000p+7f)) * 256)) + i32((max(0.0, min(0x1.000000p+0f, b)) * 0x1.fe0000p+7f)));
}
@group(0) @binding(0) var<storage, read_write> occlusion_step_outb_buf : array<i32>;
struct U_occlusion_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_occlusion_step : U_occlusion_step;
@compute @workgroup_size(64)
fn occlusion_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_occlusion_step.frame;
  let px = (gid - ((gid / oc_width) * oc_width));
  let py = (gid / oc_width);
  let fx = (f32(f32((px - oc_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((oc_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+2f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.000000p+1f / rl);
  let spin = (f32(f32(frame)) / 0x1.680000p+5f);
  let n = oc_enters(0.0, 0.0, (0.0 - 0x1.400000p+2f), dx, dy, dz, 0, spin, 0);
  let f = (f32(f32(n)) / 0x1.800000p+2f);
  occlusion_step_outb_buf[gid] = select(oc_pack((max(0.0, (f - 0x1.999998p-2f)) * 0x1.999998p+0f), min(0x1.000000p+0f, (f * 0x1.666666p+0f)), max(0.0, (0x1.ccccccp-1f - (f * 0x1.4cccccp+0f)))), (((8 * 65536) + (10 * 256)) + 16), (n == 0));
}