// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const om_width : i32 = 1024;
const om_half_w : i32 = 512;
const om_half_h : i32 = 384;
const om_count : i32 = 5;
fn om_cx(i : i32) -> f32 {
  return (cos((f32(f32(i)) * 0x1.41b088p+0f)) * 0x1.b33332p+0f);
}
fn om_cz(i : i32) -> f32 {
  return (sin((f32(f32(i)) * 0x1.41b088p+0f)) * 0x1.b33332p+0f);
}
fn om_colr(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 1)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 2)) {
  return 0x1.999998p-2f;
  } else {
  if ((i == 3)) {
  return 0x1.ccccccp-1f;
  } else {
  return 0x1.333332p-1f;
  }
  }
  }
  }
}
fn om_colg(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.000000p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.999998p-1f;
  } else {
  if ((i == 2)) {
  return 0x1.b33332p-1f;
  } else {
  if ((i == 3)) {
  return 0x1.999998p-1f;
  } else {
  return 0x1.000000p-1f;
  }
  }
  }
  }
}
fn om_colb(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 1)) {
  return 0x1.199998p-1f;
  } else {
  if ((i == 2)) {
  return 0x1.000000p-1f;
  } else {
  if ((i == 3)) {
  return 0x1.666666p-2f;
  } else {
  return 0x1.ccccccp-1f;
  }
  }
  }
  }
}
fn om_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - om_cx(i));
  let lz = (oz - om_cz(i));
  let b = (((dx * lx) + (dy * (oy + 0x1.999998p-2f))) + (dz * lz));
  let c = ((((lx * lx) + ((oy + 0x1.999998p-2f) * (oy + 0x1.999998p-2f))) + (lz * lz)) - 0x1.70a3d6p-2f);
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn om_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= om_count)) {
    return bid;
    } else {
    let t = om_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn om_shadow(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, maxt__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var maxt = maxt__a;
  var i = i__a;
  loop {
    if ((i >= om_count)) {
    return 0;
    } else {
    let t = om_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > 0x1.47ae14p-6f)) {
    if ((t < maxt)) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = maxt;
    let _mv7 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    maxt = _mv6;
    i = _mv7;
    continue;
    }
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = maxt;
    let _mv7 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    maxt = _mv6;
    i = _mv7;
    continue;
    }
    }
  }
  return 0;
}
fn om_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + 0x1.000000p+6f));
  let iz = i32((hz + 0x1.000000p+6f));
  if ((((ix + iz) - (((ix + iz) / 2) * 2)) == 0)) {
  return 0x1.666666p-2f;
  } else {
  return 0x1.333332p-1f;
  }
}
fn om_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((max(0.0, min(0x1.000000p+0f, r)) * 0x1.fe0000p+7f)) * 65536) + (i32((max(0.0, min(0x1.000000p+0f, g)) * 0x1.fe0000p+7f)) * 256)) + i32((max(0.0, min(0x1.000000p+0f, b)) * 0x1.fe0000p+7f)));
}
@group(0) @binding(0) var<storage, read_write> omnishadow_step_outb_buf : array<i32>;
struct U_omnishadow_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_omnishadow_step : U_omnishadow_step;
@compute @workgroup_size(64)
fn omnishadow_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_omnishadow_step.frame;
  let px = (gid - ((gid / om_width) * om_width));
  let py = (gid / om_width);
  let fx = (f32(f32((px - om_half_w))) / 0x1.800000p+8f);
  let fy = ((f32(f32((om_half_h - py))) / 0x1.800000p+8f) - 0x1.1eb850p-2f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.47ae14p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.999998p+0f / rl);
  let oy = 0x1.333332p+1f;
  let oz = (0.0 - 0x1.600000p+2f);
  let la = (f32(f32(frame)) / 0x1.400000p+5f);
  let lgx = (cos(la) * 0x1.999998p-1f);
  let lgy = 0x1.199998p+0f;
  let lgz = (sin(la) * 0x1.999998p-1f);
  let sid = om_nearest(0.0, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  let st = select(om_hit(0.0, oy, oz, dx, dy, dz, sid), 0x1.f40000p+9f, (sid < 0));
  let ft = select((0.0 - 0x1.000000p+0f), (((0.0 - 0x1.000000p+0f) - oy) / dy), (dy < (0.0 - 0x1.a36e2ep-14f)));
  let usefloor = select(0, select(select(0, 1, (ft < st)), 1, (sid < 0)), (ft > 0x1.0624dcp-10f));
  let hitany = select(select(0, 1, (sid >= 0)), 1, (usefloor == 1));
  if ((hitany == 0)) {
  _ = (((10 * 65536) + (12 * 256)) + 22);
  } else {
  let t = select(st, ft, (usefloor == 1));
  let hx = (dx * t);
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - om_cx(sid)) / 0x1.333332p-1f), 0.0, (usefloor == 1));
  let ny = select(((hy + 0x1.999998p-2f) / 0x1.333332p-1f), 0x1.000000p+0f, (usefloor == 1));
  let nz = select(((hz - om_cz(sid)) / 0x1.333332p-1f), 0.0, (usefloor == 1));
  let ldx = (lgx - hx);
  let ldy = (lgy - hy);
  let ldz = (lgz - hz);
  let ldist = sqrt((((ldx * ldx) + (ldy * ldy)) + (ldz * ldz)));
  let ux = (ldx / ldist);
  let uy = (ldy / ldist);
  let uz = (ldz / ldist);
  let sh = om_shadow((hx + (ux * 0x1.47ae14p-6f)), (hy + (uy * 0x1.47ae14p-6f)), (hz + (uz * 0x1.47ae14p-6f)), ux, uy, uz, (ldist - 0x1.999998p-4f), 0);
  let ndl = max(0.0, (((nx * ux) + (ny * uy)) + (nz * uz)));
  let atten = (0x1.c00000p+1f / (0x1.333332p-1f + (ldist * ldist)));
  let vis = select(0x1.000000p+0f, 0x1.eb851ep-4f, (sh == 1));
  let lit = (0x1.1eb850p-3f + (((ndl * atten) * vis) * 0x1.199998p+1f));
  let chk = select(0.0, om_checker(hx, hz), (usefloor == 1));
  let ar = select(om_colr(sid), chk, (usefloor == 1));
  let ag = select(om_colg(sid), chk, (usefloor == 1));
  let ab = select(om_colb(sid), chk, (usefloor == 1));
  omnishadow_step_outb_buf[gid] = om_pack((ar * lit), (ag * lit), (ab * lit));
  }
}