// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pa_width : i32 = 1024;
const pa_half_w : i32 = 512;
const pa_half_h : i32 = 384;
fn pa_height(u : f32, v : f32) -> f32 {
  let iv = i32((v / 0x1.180000p+6f));
  let off = select(0x1.040000p+6f, 0.0, ((iv - ((iv / 2) * 2)) == 0));
  let uu = (u + off);
  let iu = i32((uu / 0x1.040000p+7f));
  let fu = (uu - (f32(f32(iu)) * 0x1.040000p+7f));
  let fv = (v - (f32(f32(iv)) * 0x1.180000p+6f));
  let du = min(fu, (0x1.040000p+7f - fu));
  let dv = min(fv, (0x1.180000p+6f - fv));
  let d = min(du, dv);
  return min(0x1.000000p+0f, max(0.0, ((d - 0x1.000000p+2f) / 0x1.200000p+3f)));
}
fn pa_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn pa_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((pa_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((pa_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((pa_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn pa_render(gid : i32, frame : i32) -> i32 {
  let px = f32(f32((gid - ((gid / pa_width) * pa_width))));
  let py = f32(f32((gid / pa_width)));
  let vdx = ((px - f32(f32(pa_half_w))) / 0x1.a90000p+9f);
  let vdy = ((py - f32(f32(pa_half_h))) / 0x1.a90000p+9f);
  let h0 = pa_height(px, py);
  let up = (px + ((vdx * h0) * 0x1.200000p+5f));
  let vp = (py + ((vdy * h0) * 0x1.200000p+5f));
  let h = pa_height(up, vp);
  let hu1 = pa_height((up + 0x1.000000p+1f), vp);
  let hu0 = pa_height((up - 0x1.000000p+1f), vp);
  let hv1 = pa_height(up, (vp + 0x1.000000p+1f));
  let hv0 = pa_height(up, (vp - 0x1.000000p+1f));
  let nx = ((hu0 - hu1) * 0x1.c00000p+2f);
  let ny = ((hv0 - hv1) * 0x1.c00000p+2f);
  let nl = sqrt((((nx * nx) + (ny * ny)) + 0x1.000000p+0f));
  let ux = (nx / nl);
  let uy = (ny / nl);
  let uz = (0x1.000000p+0f / nl);
  let ang = (f32(f32(frame)) / 0x1.c00000p+4f);
  let lx = (cos(ang) * 0x1.333332p-1f);
  let ly = (sin(ang) * 0x1.333332p-1f);
  let lz = 0x1.3d70a2p-1f;
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ndl = max(0.0, ((((ux * lx) / ll) + ((uy * ly) / ll)) + ((uz * lz) / ll)));
  let ivp = i32((vp / 0x1.180000p+6f));
  let offp = select(0x1.040000p+6f, 0.0, ((ivp - ((ivp / 2) * 2)) == 0));
  let iup = i32(((up + offp) / 0x1.040000p+7f));
  let hue = ((iup * 2) + (ivp * 3));
  let hm = (hue - ((hue / 3) * 3));
  let br = select((0x1.28f5c2p-1f + (f32(f32(hm)) * 0x1.eb851ep-5f)), 0x1.5c28f4p-2f, (h < 0x1.000000p-2f));
  let bg = select(0x1.0a3d70p-2f, 0x1.51eb84p-2f, (h < 0x1.000000p-2f));
  let bb = select(0x1.999998p-3f, 0x1.47ae14p-2f, (h < 0x1.000000p-2f));
  let sh = (0x1.c28f5cp-3f + (ndl * 0x1.d70a3cp-1f));
  return pa_pack((br * sh), (bg * sh), (bb * sh));
}
@group(0) @binding(0) var<storage, read_write> parallax_step_outb_buf : array<i32>;
struct U_parallax_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_parallax_step : U_parallax_step;
@compute @workgroup_size(64)
fn parallax_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_parallax_step.frame;
  parallax_step_outb_buf[gid] = pa_render(gid, frame);
}