// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pi_width : i32 = 1024;
const pi_half_w : i32 = 512;
const pi_half_h : i32 = 384;
const pi_count : i32 = 6;
fn pi_env_r(dy : f32) -> f32 {
  if ((dy > 0.0)) {
  return (0x1.c28f5cp-3f + (dy * 0x1.000000p-2f));
  } else {
  return (0x1.1eb850p-2f - (dy * 0x1.999998p-4f));
  }
}
fn pi_env_g(dy : f32) -> f32 {
  if ((dy > 0.0)) {
  return (0x1.851eb8p-2f + (dy * 0x1.999998p-2f));
  } else {
  return (0x1.eb851ep-3f - (dy * 0x1.eb851ep-5f));
  }
}
fn pi_env_b(dy : f32) -> f32 {
  if ((dy > 0.0)) {
  return (0x1.3d70a2p-1f + (dy * 0x1.666666p-2f));
  } else {
  return (0x1.47ae14p-3f - (dy * 0x1.47ae14p-6f));
  }
}
fn pi_sun(dx : f32, dy : f32, dz : f32) -> f32 {
  let d = (((dx * 0x1.333332p-1f) + (dy * 0x1.5c28f4p-1f)) + (dz * (0.0 - 0x1.5c28f4p-1f)));
  if ((d > 0.0)) {
  let p = (d * d);
  return (((p * p) * p) * p);
  } else {
  return 0.0;
  }
}
fn pi_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * 0x1.266666p+0f) - 0x1.733332p+1f);
}
fn pi_rough(i : i32) -> f32 {
  return (0x1.47ae14p-5f + (f32(f32(i)) * 0x1.5c28f4p-3f));
}
fn pi_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pi_cx(i));
  let b = (((dx * lx) + (dy * oy)) + (dz * oz));
  let c = ((((lx * lx) + (oy * oy)) + (oz * oz)) - 0x1.14e3bcp-2f);
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn pi_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= pi_count)) {
    return bid;
    } else {
    let t = pi_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn pi_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn pi_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pi_clamp01(r) * 0x1.fe0000p+7f)) * 65536) + (i32((pi_clamp01(g) * 0x1.fe0000p+7f)) * 256)) + i32((pi_clamp01(b) * 0x1.fe0000p+7f)));
}
fn pi_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pi_width) * pi_width));
  let py = (gid / pi_width);
  let fx = (f32(f32((px - pi_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((pi_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+2f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.000000p+1f / rl);
  let oz = (0.0 - 0x1.400000p+2f);
  let id = pi_nearest(0.0, 0.0, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  return pi_pack((pi_env_r(dy) + pi_sun(dx, dy, dz)), (pi_env_g(dy) + pi_sun(dx, dy, dz)), (pi_env_b(dy) + pi_sun(dx, dy, dz)));
  } else {
  let t = pi_hit(0.0, 0.0, oz, dx, dy, dz, id);
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = ((hx - pi_cx(id)) / 0x1.0a3d70p-1f);
  let ny = (hy / 0x1.0a3d70p-1f);
  let nz = (hz / 0x1.0a3d70p-1f);
  let vd = (((dx * nx) + (dy * ny)) + (dz * nz));
  let rx = (dx - ((0x1.000000p+1f * vd) * nx));
  let ry = (dy - ((0x1.000000p+1f * vd) * ny));
  let rz = (dz - ((0x1.000000p+1f * vd) * nz));
  let rough = pi_rough(id);
  let er = (pi_env_r(ry) + pi_sun(rx, ry, rz));
  let eg = (pi_env_g(ry) + pi_sun(rx, ry, rz));
  let eb = (pi_env_b(ry) + pi_sun(rx, ry, rz));
  let mr = ((er * (0x1.000000p+0f - rough)) + (0x1.ae147ap-2f * rough));
  let mg = ((eg * (0x1.000000p+0f - rough)) + (0x1.d70a3cp-2f * rough));
  let mb = ((eb * (0x1.000000p+0f - rough)) + (0x1.199998p-1f * rough));
  let fres = (0x1.47ae14p-4f + ((0x1.d70a3cp-1f * pi_clamp01((0x1.000000p+0f + vd))) * pi_clamp01((0x1.000000p+0f + vd))));
  let tint_r = 0x1.e66666p-1f;
  let tint_g = 0x1.8f5c28p-1f;
  let tint_b = 0x1.ccccccp-2f;
  return pi_pack(((mr * tint_r) * (0x1.000000p-1f + (fres * 0x1.333332p-1f))), ((mg * tint_g) * (0x1.000000p-1f + (fres * 0x1.333332p-1f))), ((mb * tint_b) * (0x1.000000p-1f + (fres * 0x1.333332p-1f))));
  }
}
@group(0) @binding(0) var<storage, read_write> pbribl_step_outb_buf : array<i32>;
struct U_pbribl_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbribl_step : U_pbribl_step;
@compute @workgroup_size(64)
fn pbribl_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbribl_step.frame;
  pbribl_step_outb_buf[gid] = pi_render(gid, frame);
}