// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pb_width : i32 = 1024;
const pb_half_w : i32 = 512;
const pb_half_h : i32 = 384;
const pb_count : i32 = 7;
fn pb_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * 0x1.266666p+0f) - 0x1.b99998p+1f);
}
fn pb_rough(i : i32) -> f32 {
  return (0x1.eb851ep-5f + (f32(f32(i)) * 0x1.28f5c2p-3f));
}
const pb_rad : f32 = 0x1.0a3d70p-1f;
fn pb_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pb_cx(i));
  let ly = oy;
  let lz = oz;
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (pb_rad * pb_rad));
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn pb_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= pb_count)) {
    return best_id;
    } else {
    let t = pb_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn pb_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn pb_pow5(x : f32) -> f32 {
  let x2 = (x * x);
  return ((x2 * x2) * x);
}
fn pb_ggx(ndh : f32, a : f32) -> f32 {
  let a2 = (a * a);
  let d = (((ndh * ndh) * (a2 - 0x1.000000p+0f)) + 0x1.000000p+0f);
  return (a2 / ((d * d) + 0x1.a36e2ep-14f));
}
fn pb_g1(nx : f32, k : f32) -> f32 {
  return (nx / (((nx * (0x1.000000p+0f - k)) + k) + 0x1.a36e2ep-14f));
}
fn pb_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((pb_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((pb_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((pb_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn pb_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / 0x1.800000p+9f);
  return pb_pack((0x1.eb851ep-6f + (h * 0x1.999998p-5f)), (0x1.47ae14p-5f + (h * 0x1.eb851ep-5f)), (0x1.eb851ep-5f + (h * 0x1.999998p-4f)));
}
fn pb_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pb_width) * pb_width));
  let py = (gid / pb_width);
  let fx = (f32(f32((px - pb_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((pb_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+2f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.000000p+1f / rl);
  let ox = 0.0;
  let oy = 0.0;
  let oz = (0.0 - 0x1.400000p+2f);
  let id = pb_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  return pb_bg(py);
  } else {
  let t = pb_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = ((hx - pb_cx(id)) / pb_rad);
  let ny = (hy / pb_rad);
  let nz = (hz / pb_rad);
  let ang = (f32(f32(frame)) / 0x1.400000p+5f);
  let lx0 = ((cos(ang) * 0x1.000000p-1f) + 0x1.333332p-2f);
  let ly0 = 0x1.666666p-1f;
  let lz0 = ((sin(ang) * 0x1.000000p-1f) - 0x1.000000p-1f);
  let ll = sqrt((((lx0 * lx0) + (ly0 * ly0)) + (lz0 * lz0)));
  let lx = (lx0 / ll);
  let ly = (ly0 / ll);
  let lz = (lz0 / ll);
  let vx = (0.0 - dx);
  let vy = (0.0 - dy);
  let vz = (0.0 - dz);
  let hlx = (lx + vx);
  let hly = (ly + vy);
  let hlz = (lz + vz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + 0x1.a36e2ep-14f);
  let hnx = (hlx / hl);
  let hny = (hly / hl);
  let hnz = (hlz / hl);
  let ndl = max(0.0, (((nx * lx) + (ny * ly)) + (nz * lz)));
  let ndv = max(0.0, (((nx * vx) + (ny * vy)) + (nz * vz)));
  let ndh = max(0.0, (((nx * hnx) + (ny * hny)) + (nz * hnz)));
  let vdh = max(0.0, (((vx * hnx) + (vy * hny)) + (vz * hnz)));
  let rough = pb_rough(id);
  let a = (rough * rough);
  let k = (a * 0x1.000000p-1f);
  let dggx = pb_ggx(ndh, a);
  let gsm = (pb_g1(ndv, k) * pb_g1(ndl, k));
  let fres = (0x1.47ae14p-5f + (0x1.eb851ep-1f * pb_pow5((0x1.000000p+0f - vdh))));
  let spec = (((dggx * gsm) * fres) / (((0x1.000000p+2f * ndv) * ndl) + 0x1.47ae14p-7f));
  let kd = (0x1.000000p+0f - fres);
  let dr = (0x1.ccccccp-1f * kd);
  let dg = (0x1.70a3d6p-1f * kd);
  let db = (0x1.333332p-2f * kd);
  let sr = (((dr + spec) * ndl) + 0x1.999998p-5f);
  let sg = (((dg + spec) * ndl) + 0x1.eb851ep-5f);
  let sb = (((db + spec) * ndl) + 0x1.47ae14p-4f);
  return pb_pack(sr, sg, sb);
  }
}
@group(0) @binding(0) var<storage, read_write> pbr_step_outb_buf : array<i32>;
struct U_pbr_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbr_step : U_pbr_step;
@compute @workgroup_size(64)
fn pbr_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbr_step.frame;
  pbr_step_outb_buf[gid] = pb_render(gid, frame);
}