// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pt_width : i32 = 1024;
const pt_half_w : i32 = 512;
const pt_half_h : i32 = 384;
fn pt_tex_r(iu : i32, iv : i32) -> f32 {
  let m = (((iu * 3) + (iv * 5)) - ((((iu * 3) + (iv * 5)) / 4) * 4));
  return (0x1.ccccccp-2f + (f32(f32(m)) * 0x1.eb851ep-4f));
}
fn pt_tex_g(iu : i32, iv : i32) -> f32 {
  let m = ((iu + (iv * 2)) - (((iu + (iv * 2)) / 3) * 3));
  return (0x1.999998p-2f + (f32(f32(m)) * 0x1.47ae14p-3f));
}
fn pt_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn pt_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pt_clamp01(r) * 0x1.fe0000p+7f)) * 65536) + (i32((pt_clamp01(g) * 0x1.fe0000p+7f)) * 256)) + i32((pt_clamp01(b) * 0x1.fe0000p+7f)));
}
fn pt_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pt_width) * pt_width));
  let py = (gid / pt_width);
  let fx = (f32(f32((px - pt_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((pt_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+2f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.000000p+1f / rl);
  let oz = (0.0 - 0x1.000000p+2f);
  let b = (dz * oz);
  let c = ((oz * oz) - 0x1.999998p+0f);
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  let h = pt_clamp01(((dy * 0x1.000000p-1f) + 0x1.000000p-1f));
  return pt_pack((0x1.999998p-5f + (h * 0x1.999998p-5f)), (0x1.eb851ep-5f + (h * 0x1.47ae14p-4f)), (0x1.999998p-4f + (h * 0x1.333332p-3f)));
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = (hx / 0x1.43d70ap+0f);
  let ny = (hy / 0x1.43d70ap+0f);
  let nz = (hz / 0x1.43d70ap+0f);
  let spin = (f32(f32(frame)) / 0x1.400000p+5f);
  let u = ((((cos(spin) * nx) + (sin(spin) * nz)) * 0x1.000000p-1f) + 0x1.000000p-1f);
  let v = ((ny * 0x1.000000p-1f) + 0x1.000000p-1f);
  let iu = i32((u * 0x1.800000p+3f));
  let iv = i32((v * 0x1.000000p+3f));
  let fu = ((u * 0x1.800000p+3f) - f32(f32(iu)));
  let fv = ((v * 0x1.000000p+3f) - f32(f32(iv)));
  let grout = select(select(0, 1, (fv < 0x1.47ae14p-4f)), 1, (fu < 0x1.47ae14p-4f));
  let ar = select(pt_tex_r(iu, iv), 0x1.1eb850p-3f, (grout == 1));
  let ag = select(pt_tex_g(iu, iv), 0x1.1eb850p-3f, (grout == 1));
  let ab = select(0x1.199998p-1f, 0x1.47ae14p-3f, (grout == 1));
  let la = (f32(f32(frame)) / 0x1.e00000p+4f);
  let lx = (cos(la) * 0x1.333332p-1f);
  let ly = 0x1.666666p-1f;
  let lz = ((sin(la) * 0x1.333332p-1f) - 0x1.333332p-2f);
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let hlx = (ux - dx);
  let hly = (uy - dy);
  let hlz = (uz - dz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + 0x1.0624dcp-10f);
  let ndh = max(0.0, ((((nx * hlx) / hl) + ((ny * hly) / hl)) + ((nz * hlz) / hl)));
  let ndl = max(0.0, (((nx * ux) + (ny * uy)) + (nz * uz)));
  let a2 = 0x1.70a3d6p-4f;
  let dd = (((ndh * ndh) * (a2 - 0x1.000000p+0f)) + 0x1.000000p+0f);
  let spec = ((a2 / ((dd * dd) + 0x1.0624dcp-10f)) * 0x1.999998p-2f);
  let sh = (0x1.333332p-3f + (ndl * 0x1.b33332p-1f));
  return pt_pack(((ar * sh) + spec), ((ag * sh) + spec), ((ab * sh) + spec));
  }
}
@group(0) @binding(0) var<storage, read_write> pbrtex_step_outb_buf : array<i32>;
struct U_pbrtex_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbrtex_step : U_pbrtex_step;
@compute @workgroup_size(64)
fn pbrtex_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbrtex_step.frame;
  pbrtex_step_outb_buf[gid] = pt_render(gid, frame);
}