// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pl_width : i32 = 1024;
const pl_half_w : i32 = 512;
const pl_half_h : i32 = 384;
const pl_count : i32 = 6;
fn pl_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * 0x1.333332p+0f) - 0x1.800000p+1f);
}
fn pl_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pl_cx(i));
  let b = (((dx * lx) + (dy * oy)) + (dz * oz));
  let c = ((((lx * lx) + (oy * oy)) + (oz * oz)) - 0x1.35c28ep-2f);
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn pl_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= pl_count)) {
    return bid;
    } else {
    let t = pl_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn pl_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn pl_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pl_clamp01(r) * 0x1.fe0000p+7f)) * 65536) + (i32((pl_clamp01(g) * 0x1.fe0000p+7f)) * 256)) + i32((pl_clamp01(b) * 0x1.fe0000p+7f)));
}
fn pl_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pl_width) * pl_width));
  let py = (gid / pl_width);
  let fx = (f32(f32((px - pl_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((pl_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.000000p+2f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.000000p+1f / rl);
  let oz = (0.0 - 0x1.400000p+2f);
  let id = pl_nearest(0.0, 0.0, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  let h = pl_clamp01(((dy * 0x1.000000p-1f) + 0x1.000000p-1f));
  return pl_pack((0x1.999998p-5f + (h * 0x1.999998p-5f)), (0x1.eb851ep-5f + (h * 0x1.47ae14p-4f)), (0x1.999998p-4f + (h * 0x1.1eb850p-3f)));
  } else {
  let t = pl_hit(0.0, 0.0, oz, dx, dy, dz, id);
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = ((hx - pl_cx(id)) / 0x1.199998p-1f);
  let ny = (hy / 0x1.199998p-1f);
  let nz = (hz / 0x1.199998p-1f);
  let la = (f32(f32(frame)) / 0x1.e00000p+4f);
  let lx = (cos(la) * 0x1.000000p-1f);
  let ly = 0x1.666666p-1f;
  let lz = ((sin(la) * 0x1.000000p-1f) - 0x1.999998p-2f);
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ndl = max(0.0, ((((nx * lx) / ll) + ((ny * ly) / ll)) + ((nz * lz) / ll)));
  let vdn = (0.0 - (((dx * nx) + (dy * ny)) + (dz * nz)));
  let hlx = ((lx / ll) - dx);
  let hly = ((ly / ll) - dy);
  let hlz = ((lz / ll) - dz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + 0x1.0624dcp-10f);
  let spec = max(0.0, ((((nx * hlx) / hl) + ((ny * hly) / hl)) + ((nz * hlz) / hl)));
  let s2 = (spec * spec);
  let s8 = (((s2 * s2) * s2) * s2);
  if ((id == 0)) {
  return pl_pack(0x1.199998p-1f, 0x1.666666p-2f, 0x1.800000p-1f);
  } else {
  if ((id == 1)) {
  return pl_pack((0x1.333332p-2f * (0x1.999998p-3f + ndl)), (0x1.333332p-1f * (0x1.999998p-3f + ndl)), (0x1.ccccccp-1f * (0x1.999998p-3f + ndl)));
  } else {
  if ((id == 2)) {
  return pl_pack(((0x1.b33332p-1f * ndl) + s8), ((0x1.000000p-1f * ndl) + s8), ((0x1.333332p-2f * ndl) + s8));
  } else {
  if ((id == 3)) {
  let band = select(select(select(0x1.70a3d6p-3f, 0x1.851eb8p-2f, (ndl > 0x1.333332p-3f)), 0x1.4cccccp-1f, (ndl > 0x1.999998p-2f)), 0x1.000000p+0f, (ndl > 0x1.800000p-1f));
  return pl_pack((0x1.ccccccp-1f * band), (0x1.199998p-1f * band), (0x1.666666p-2f * band));
  } else {
  if ((id == 4)) {
  return pl_pack(((nx * 0x1.000000p-1f) + 0x1.000000p-1f), ((ny * 0x1.000000p-1f) + 0x1.000000p-1f), ((nz * 0x1.000000p-1f) + 0x1.000000p-1f));
  } else {
  let fres = pl_clamp01((0x1.000000p+0f - vdn));
  let f5 = ((((fres * fres) * fres) * fres) * fres);
  return pl_pack((0x1.999998p-4f + (f5 * 0x1.ccccccp-1f)), (0x1.333332p-3f + (f5 * 0x1.b33332p-1f)), (0x1.000000p-2f + (f5 * 0x1.800000p-1f)));
  }
  }
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> pipelines_step_outb_buf : array<i32>;
struct U_pipelines_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pipelines_step : U_pipelines_step;
@compute @workgroup_size(64)
fn pipelines_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pipelines_step.frame;
  pipelines_step_outb_buf[gid] = pl_render(gid, frame);
}