// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rd_width : i32 = 1024;
const rd_half_w : i32 = 512;
const rd_half_h : i32 = 384;
const rd_taps : i32 = 28;
fn rd_clamp(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
fn rd_extract(texel : i32, ch : i32) -> i32 {
  if ((ch == 0)) {
  return (texel / 65536);
  } else {
  if ((ch == 1)) {
  return ((texel / 256) - ((texel / 65536) * 256));
  } else {
  return (texel - ((texel / 256) * 256));
  }
  }
}
fn rd_gather(px__a : i32, py__a : i32, ch__a : i32, k__a : i32, acc__a : i32) -> i32 {
  var px = px__a;
  var py = py__a;
  var ch = ch__a;
  var k = k__a;
  var acc = acc__a;
  loop {
    if ((k >= rd_taps)) {
    return acc;
    } else {
    let scale = (0x1.000000p+0f - (f32(f32(k)) * 0x1.eb851ep-8f));
    let sx = (rd_half_w + i32((f32(f32((px - rd_half_w))) * scale)));
    let sy = (rd_half_h + i32((f32(f32((py - rd_half_h))) * scale)));
    let cx = rd_clamp(sx, 0, 1023);
    let cy = rd_clamp(sy, 0, 767);
    let idx = ((cy * 1024) + cx);
    let texel = radial_step_scenebuf_buf[idx];
    let c = rd_extract(texel, ch);
    let _mv1 = px;
    let _mv2 = py;
    let _mv3 = ch;
    let _mv4 = (k + 1);
    let _mv5 = (acc + c);
    px = _mv1;
    py = _mv2;
    ch = _mv3;
    k = _mv4;
    acc = _mv5;
    continue;
    }
  }
  return 0;
}
@group(0) @binding(0) var<storage, read_write> radial_step_scenebuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> radial_step_outb_buf : array<i32>;
struct U_radial_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_radial_step : U_radial_step;
@compute @workgroup_size(64)
fn radial_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_radial_step.frame;
  let px = (gid - ((gid / rd_width) * rd_width));
  let py = (gid / rd_width);
  let own = radial_step_scenebuf_buf[gid];
  let rr = rd_gather(px, py, 0, 0, 0);
  let rg = rd_gather(px, py, 1, 0, 0);
  let rb = rd_gather(px, py, 2, 0, 0);
  let fr = rd_clamp(((rr / rd_taps) + (rd_extract(own, 0) / 3)), 0, 255);
  let fg = rd_clamp(((rg / rd_taps) + (rd_extract(own, 1) / 3)), 0, 255);
  let fb = rd_clamp(((rb / rd_taps) + (rd_extract(own, 2) / 3)), 0, 255);
  radial_step_outb_buf[gid] = (((fr * 65536) + (fg * 256)) + fb);
}