// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rt_width : i32 = 1024;
const rt_half_w : i32 = 512;
const rt_half_h : i32 = 384;
const rt_nobj : i32 = 4;
fn rt_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.b33332p+0f);
  } else {
  return 0x1.999998p+0f;
  }
  }
}
fn rt_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.666666p-2f);
  } else {
  return (0.0 - 0x1.ccccccp-2f);
  }
  }
}
fn rt_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return 0x1.000000p-1f;
  } else {
  return (0.0 - 0x1.999998p-2f);
  }
  }
}
fn rt_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.000000p+0f;
  } else {
  if ((i == 1)) {
  return 0x1.4cccccp-1f;
  } else {
  return 0x1.199998p-1f;
  }
  }
}
fn rt_col_r(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.e66666p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.999998p-3f;
  } else {
  return 0x1.666666p-1f;
  }
  }
}
fn rt_col_g(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.ccccccp-2f;
  } else {
  if ((i == 1)) {
  return 0x1.999998p-1f;
  } else {
  return 0x1.666666p-2f;
  }
  }
}
fn rt_col_b(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.c28f5cp-3f;
  } else {
  if ((i == 1)) {
  return 0x1.800000p-1f;
  } else {
  return 0x1.e66666p-1f;
  }
  }
}
fn rt_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - rt_cx(i));
  let ly = (oy - rt_cy(i));
  let lz = (oz - rt_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = rt_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn rt_plane_hit(oy : f32, dy : f32) -> f32 {
  if ((dy > (0.0 - 0x1.a36e2ep-14f))) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = (((0.0 - 0x1.000000p+0f) - oy) / dy);
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn rt_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32) -> f32 {
  if ((id == 3)) {
  return rt_plane_hit(oy, dy);
  } else {
  return rt_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  }
}
fn rt_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= rt_nobj)) {
    return best_id;
    } else {
    let t = rt_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn rt_shadowed(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  loop {
    if ((i >= 3)) {
    return 0;
    } else {
    let t = rt_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > 0x1.0624dcp-10f)) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    continue;
    }
    }
  }
  return 0;
}
fn rt_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn rt_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((rt_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((rt_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((rt_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn rt_sky(dy : f32) -> i32 {
  let h = rt_clamp01(((dy * 0x1.000000p-1f) + 0x1.000000p-1f));
  return rt_pack((0x1.999998p-5f + (h * 0x1.eb851ep-5f)), (0x1.70a3d6p-4f + (h * 0x1.1eb850p-3f)), (0x1.c28f5cp-3f + (h * 0x1.5c28f4p-2f)));
}
fn rt_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + 0x1.000000p+6f));
  let iz = i32((hz + 0x1.000000p+6f));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return 0x1.47ae14p-2f;
  } else {
  return 0x1.3d70a2p-1f;
  }
}
fn rt_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / rt_width) * rt_width));
  let py = (gid / rt_width);
  let fx = (f32(f32((px - rt_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((rt_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.71eb84p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.b33332p+0f / rl);
  let ox = 0.0;
  let oy = 0x1.666666p-1f;
  let oz = (0.0 - 0x1.000000p+2f);
  let id = rt_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  return rt_sky(dy);
  } else {
  let t = rt_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - rt_cx(id)) / rt_rad(id)), 0.0, (id == 3));
  let ny = select(((hy - rt_cy(id)) / rt_rad(id)), 0x1.000000p+0f, (id == 3));
  let nz = select(((hz - rt_cz(id)) / rt_rad(id)), 0.0, (id == 3));
  let br = select(rt_col_r(id), rt_checker(hx, hz), (id == 3));
  let bg = select(rt_col_g(id), rt_checker(hx, hz), (id == 3));
  let bb = select(rt_col_b(id), rt_checker(hx, hz), (id == 3));
  let ang = (f32(f32(frame)) / 0x1.800000p+4f);
  let lx = (cos(ang) * 0x1.333332p-1f);
  let ly = 0x1.ccccccp-1f;
  let lz = (sin(ang) * 0x1.333332p-1f);
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let ndl = max(0.0, (((nx * ux) + (ny * uy)) + (nz * uz)));
  let sx = (hx + (nx * 0x1.0624dcp-9f));
  let sy = (hy + (ny * 0x1.0624dcp-9f));
  let sz = (hz + (nz * 0x1.0624dcp-9f));
  let sh = rt_shadowed(sx, sy, sz, ux, uy, uz, 0);
  let lit = select((0x1.999998p-3f + (ndl * 0x1.ccccccp-1f)), 0x1.999998p-3f, (sh == 1));
  return rt_pack((br * lit), (bg * lit), (bb * lit));
  }
}
@group(0) @binding(0) var<storage, read_write> raytrace_step_outb_buf : array<i32>;
struct U_raytrace_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_raytrace_step : U_raytrace_step;
@compute @workgroup_size(64)
fn raytrace_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_raytrace_step.frame;
  raytrace_step_outb_buf[gid] = rt_render(gid, frame);
}