// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rf_width : i32 = 1024;
const rf_half_w : i32 = 512;
const rf_half_h : i32 = 384;
const rf_nobj : i32 = 4;
fn rf_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.b33332p+0f);
  } else {
  return 0x1.999998p+0f;
  }
  }
}
fn rf_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.666666p-2f);
  } else {
  return (0.0 - 0x1.ccccccp-2f);
  }
  }
}
fn rf_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return 0x1.000000p-1f;
  } else {
  return (0.0 - 0x1.999998p-2f);
  }
  }
}
fn rf_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.000000p+0f;
  } else {
  if ((i == 1)) {
  return 0x1.4cccccp-1f;
  } else {
  return 0x1.199998p-1f;
  }
  }
}
fn rf_col_r(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.e66666p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.000000p-2f;
  } else {
  return 0x1.800000p-1f;
  }
  }
}
fn rf_col_g(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.199998p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.b33332p-1f;
  } else {
  return 0x1.999998p-2f;
  }
  }
}
fn rf_col_b(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.333332p-2f;
  } else {
  if ((i == 1)) {
  return 0x1.999998p-1f;
  } else {
  return 0x1.f5c28ep-1f;
  }
  }
}
fn rf_refl(i : i32) -> f32 {
  if ((i == 3)) {
  return 0x1.333332p-2f;
  } else {
  return 0x1.199998p-1f;
  }
}
fn rf_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - rf_cx(i));
  let ly = (oy - rf_cy(i));
  let lz = (oz - rf_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = rf_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn rf_plane_hit(oy : f32, dy : f32) -> f32 {
  if ((dy > (0.0 - 0x1.a36e2ep-14f))) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = (((0.0 - 0x1.000000p+0f) - oy) / dy);
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn rf_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32) -> f32 {
  if ((id == 3)) {
  return rf_plane_hit(oy, dy);
  } else {
  return rf_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  }
}
fn rf_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= rf_nobj)) {
    return best_id;
    } else {
    let t = rf_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn rf_shadowed(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  loop {
    if ((i >= 3)) {
    return 0;
    } else {
    let t = rf_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > 0x1.0624dcp-10f)) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    continue;
    }
    }
  }
  return 0;
}
fn rf_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn rf_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((rf_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((rf_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((rf_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn rf_sky(dy : f32) -> i32 {
  let h = rf_clamp01(((dy * 0x1.000000p-1f) + 0x1.000000p-1f));
  return rf_pack((0x1.999998p-5f + (h * 0x1.eb851ep-5f)), (0x1.999998p-4f + (h * 0x1.47ae14p-3f)), (0x1.eb851ep-3f + (h * 0x1.999998p-2f)));
}
fn rf_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + 0x1.000000p+6f));
  let iz = i32((hz + 0x1.000000p+6f));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return 0x1.666666p-2f;
  } else {
  return 0x1.4cccccp-1f;
  }
}
fn rf_un_r(p : i32) -> f32 {
  return (f32(f32((p / 65536))) / 0x1.fe0000p+7f);
}
fn rf_un_g(p : i32) -> f32 {
  return (f32(f32(((p / 256) - ((p / 65536) * 256)))) / 0x1.fe0000p+7f);
}
fn rf_un_b(p : i32) -> f32 {
  return (f32(f32((p - ((p / 256) * 256)))) / 0x1.fe0000p+7f);
}
fn rf_local(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32, frame : i32) -> i32 {
  let t = rf_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - rf_cx(id)) / rf_rad(id)), 0.0, (id == 3));
  let ny = select(((hy - rf_cy(id)) / rf_rad(id)), 0x1.000000p+0f, (id == 3));
  let nz = select(((hz - rf_cz(id)) / rf_rad(id)), 0.0, (id == 3));
  let br = select(rf_col_r(id), rf_checker(hx, hz), (id == 3));
  let bg = select(rf_col_g(id), rf_checker(hx, hz), (id == 3));
  let bb = select(rf_col_b(id), rf_checker(hx, hz), (id == 3));
  let ang = (f32(f32(frame)) / 0x1.800000p+4f);
  let lx = (cos(ang) * 0x1.333332p-1f);
  let ly = 0x1.ccccccp-1f;
  let lz = (sin(ang) * 0x1.333332p-1f);
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let ndl = max(0.0, (((nx * ux) + (ny * uy)) + (nz * uz)));
  let sh = rf_shadowed((hx + (nx * 0x1.0624dcp-9f)), (hy + (ny * 0x1.0624dcp-9f)), (hz + (nz * 0x1.0624dcp-9f)), ux, uy, uz, 0);
  let lit = select((0x1.c28f5cp-3f + (ndl * 0x1.ccccccp-1f)), 0x1.c28f5cp-3f, (sh == 1));
  return rf_pack((br * lit), (bg * lit), (bb * lit));
}
fn rf_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / rf_width) * rf_width));
  let py = (gid / rf_width);
  let fx = (f32(f32((px - rf_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((rf_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.71eb84p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.b33332p+0f / rl);
  let ox = 0.0;
  let oy = 0x1.666666p-1f;
  let oz = (0.0 - 0x1.000000p+2f);
  let id0 = rf_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id0 < 0)) {
  return rf_sky(dy);
  } else {
  let t0 = rf_hit(ox, oy, oz, dx, dy, dz, id0);
  let hx = (ox + (dx * t0));
  let hy = (oy + (dy * t0));
  let hz = (oz + (dz * t0));
  let nx = select(((hx - rf_cx(id0)) / rf_rad(id0)), 0.0, (id0 == 3));
  let ny = select(((hy - rf_cy(id0)) / rf_rad(id0)), 0x1.000000p+0f, (id0 == 3));
  let nz = select(((hz - rf_cz(id0)) / rf_rad(id0)), 0.0, (id0 == 3));
  let p0 = rf_local(ox, oy, oz, dx, dy, dz, id0, frame);
  let dn = (((dx * nx) + (dy * ny)) + (dz * nz));
  let rx = (dx - ((0x1.000000p+1f * dn) * nx));
  let ry = (dy - ((0x1.000000p+1f * dn) * ny));
  let rz = (dz - ((0x1.000000p+1f * dn) * nz));
  let sx = (hx + (nx * 0x1.89374ap-9f));
  let sy = (hy + (ny * 0x1.89374ap-9f));
  let sz = (hz + (nz * 0x1.89374ap-9f));
  let id1 = rf_nearest(sx, sy, sz, rx, ry, rz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  let pr = select(rf_local(sx, sy, sz, rx, ry, rz, id1, frame), rf_sky(ry), (id1 < 0));
  let k = rf_refl(id0);
  let cr = ((rf_un_r(p0) * (0x1.000000p+0f - k)) + (rf_un_r(pr) * k));
  let cg = ((rf_un_g(p0) * (0x1.000000p+0f - k)) + (rf_un_g(pr) * k));
  let cb = ((rf_un_b(p0) * (0x1.000000p+0f - k)) + (rf_un_b(pr) * k));
  return rf_pack(cr, cg, cb);
  }
}
@group(0) @binding(0) var<storage, read_write> reflect_step_outb_buf : array<i32>;
struct U_reflect_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_reflect_step : U_reflect_step;
@compute @workgroup_size(64)
fn reflect_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_reflect_step.frame;
  reflect_step_outb_buf[gid] = rf_render(gid, frame);
}