// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const sd_width : i32 = 1024;
const sd_half_w : i32 = 512;
const sd_half_h : i32 = 384;
const sd_nobj : i32 = 4;
const sd_samples : i32 = 9;
fn sd_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.b33332p+0f);
  } else {
  return 0x1.999998p+0f;
  }
  }
}
fn sd_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return (0.0 - 0x1.666666p-2f);
  } else {
  return (0.0 - 0x1.ccccccp-2f);
  }
  }
}
fn sd_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return 0.0;
  } else {
  if ((i == 1)) {
  return 0x1.000000p-1f;
  } else {
  return (0.0 - 0x1.999998p-2f);
  }
  }
}
fn sd_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.000000p+0f;
  } else {
  if ((i == 1)) {
  return 0x1.4cccccp-1f;
  } else {
  return 0x1.199998p-1f;
  }
  }
}
fn sd_col_r(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.ccccccp-1f;
  } else {
  if ((i == 1)) {
  return 0x1.666666p-2f;
  } else {
  return 0x1.999998p-1f;
  }
  }
}
fn sd_col_g(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.199998p-1f;
  } else {
  if ((i == 1)) {
  return 0x1.800000p-1f;
  } else {
  return 0x1.ccccccp-2f;
  }
  }
}
fn sd_col_b(i : i32) -> f32 {
  if ((i == 0)) {
  return 0x1.666666p-2f;
  } else {
  if ((i == 1)) {
  return 0x1.199998p-1f;
  } else {
  return 0x1.e66666p-1f;
  }
  }
}
fn sd_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - sd_cx(i));
  let ly = (oy - sd_cy(i));
  let lz = (oz - sd_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = sd_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < 0.0)) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = ((0.0 - b) - sqrt(disc));
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn sd_plane_hit(oy : f32, dy : f32) -> f32 {
  if ((dy > (0.0 - 0x1.a36e2ep-14f))) {
  return (0.0 - 0x1.000000p+0f);
  } else {
  let t = (((0.0 - 0x1.000000p+0f) - oy) / dy);
  if ((t > 0x1.0624dcp-10f)) {
  return t;
  } else {
  return (0.0 - 0x1.000000p+0f);
  }
  }
}
fn sd_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32) -> f32 {
  if ((id == 3)) {
  return sd_plane_hit(oy, dy);
  } else {
  return sd_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  }
}
fn sd_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= sd_nobj)) {
    return best_id;
    } else {
    let t = sd_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < 0.0)), (t > 0x1.0624dcp-10f));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
  return 0;
}
fn sd_occluded(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  loop {
    if ((i >= 3)) {
    return 0;
    } else {
    let t = sd_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > 0x1.0624dcp-10f)) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    continue;
    }
    }
  }
  return 0;
}
fn sd_off_x(i : i32) -> f32 {
  return (f32(f32(((i - ((i / 3) * 3)) - 1))) * 0x1.199998p+0f);
}
fn sd_off_z(i : i32) -> f32 {
  return (f32(f32(((i / 3) - 1))) * 0x1.199998p+0f);
}
fn sd_soft(hx__a : f32, hy__a : f32, hz__a : f32, lx__a : f32, lz__a : f32, i__a : i32, acc__a : i32) -> i32 {
  var hx = hx__a;
  var hy = hy__a;
  var hz = hz__a;
  var lx = lx__a;
  var lz = lz__a;
  var i = i__a;
  var acc = acc__a;
  loop {
    if ((i >= sd_samples)) {
    return acc;
    } else {
    let ddx = ((lx + sd_off_x(i)) - hx);
    let ddy = (0x1.800000p+2f - hy);
    let ddz = ((lz + sd_off_z(i)) - hz);
    let dl = sqrt((((ddx * ddx) + (ddy * ddy)) + (ddz * ddz)));
    let ux = (ddx / dl);
    let uy = (ddy / dl);
    let uz = (ddz / dl);
    let occ = sd_occluded((hx + (ux * 0x1.89374ap-9f)), (hy + (uy * 0x1.89374ap-9f)), (hz + (uz * 0x1.89374ap-9f)), ux, uy, uz, 0);
    let vis = select(1, 0, (occ == 1));
    let _mv0 = hx;
    let _mv1 = hy;
    let _mv2 = hz;
    let _mv3 = lx;
    let _mv4 = lz;
    let _mv5 = (i + 1);
    let _mv6 = (acc + vis);
    hx = _mv0;
    hy = _mv1;
    hz = _mv2;
    lx = _mv3;
    lz = _mv4;
    i = _mv5;
    acc = _mv6;
    continue;
    }
  }
  return 0;
}
fn sd_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn sd_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((sd_clamp01(r) * 0x1.fe0000p+7f));
  let gi = i32((sd_clamp01(g) * 0x1.fe0000p+7f));
  let bi = i32((sd_clamp01(b) * 0x1.fe0000p+7f));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn sd_sky(dy : f32) -> i32 {
  let h = sd_clamp01(((dy * 0x1.000000p-1f) + 0x1.000000p-1f));
  return sd_pack((0x1.eb851ep-5f + (h * 0x1.1eb850p-4f)), (0x1.999998p-4f + (h * 0x1.333332p-3f)), (0x1.eb851ep-3f + (h * 0x1.999998p-2f)));
}
fn sd_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + 0x1.000000p+6f));
  let iz = i32((hz + 0x1.000000p+6f));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return 0x1.851eb8p-2f;
  } else {
  return 0x1.51eb84p-1f;
  }
}
fn sd_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / sd_width) * sd_width));
  let py = (gid / sd_width);
  let fx = (f32(f32((px - sd_half_w))) / 0x1.800000p+8f);
  let fy = (f32(f32((sd_half_h - py))) / 0x1.800000p+8f);
  let rl = sqrt((((fx * fx) + (fy * fy)) + 0x1.71eb84p+1f));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (0x1.b33332p+0f / rl);
  let ox = 0.0;
  let oy = 0x1.666666p-1f;
  let oz = (0.0 - 0x1.000000p+2f);
  let id = sd_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (0.0 - 0x1.000000p+0f));
  if ((id < 0)) {
  return sd_sky(dy);
  } else {
  let t = sd_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - sd_cx(id)) / sd_rad(id)), 0.0, (id == 3));
  let ny = select(((hy - sd_cy(id)) / sd_rad(id)), 0x1.000000p+0f, (id == 3));
  let nz = select(((hz - sd_cz(id)) / sd_rad(id)), 0.0, (id == 3));
  let br = select(sd_col_r(id), sd_checker(hx, hz), (id == 3));
  let bg = select(sd_col_g(id), sd_checker(hx, hz), (id == 3));
  let bb = select(sd_col_b(id), sd_checker(hx, hz), (id == 3));
  let ang = (f32(f32(frame)) / 0x1.e00000p+4f);
  let lx = (cos(ang) * 0x1.800000p+1f);
  let lz = (sin(ang) * 0x1.800000p+1f);
  let lcx = (lx - hx);
  let lcy = (0x1.800000p+2f - hy);
  let lcz = (lz - hz);
  let lcl = sqrt((((lcx * lcx) + (lcy * lcy)) + (lcz * lcz)));
  let ndl = max(0.0, ((((nx * lcx) / lcl) + ((ny * lcy) / lcl)) + ((nz * lcz) / lcl)));
  let vis = (f32(f32(sd_soft(hx, hy, hz, lx, lz, 0, 0))) / 0x1.200000p+3f);
  let lit = (0x1.70a3d6p-3f + ((ndl * 0x1.d70a3cp-1f) * vis));
  return sd_pack((br * lit), (bg * lit), (bb * lit));
  }
}
@group(0) @binding(0) var<storage, read_write> shadow_step_outb_buf : array<i32>;
struct U_shadow_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_shadow_step : U_shadow_step;
@compute @workgroup_size(64)
fn shadow_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_shadow_step.frame;
  shadow_step_outb_buf[gid] = sd_render(gid, frame);
}