// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const st_width : i32 = 1024;
fn st_atan2(y : f32, x : f32) -> f32 {
  let ax = select(x, (0.0 - x), (x < 0.0));
  let ay = select(y, (0.0 - y), (y < 0.0));
  let mn = min(ax, ay);
  let mx = max(ax, ay);
  let a = select(0.0, (mn / mx), (mx > 0.0));
  let a2 = (a * a);
  let base = ((a * (0x1.a40000p+6f + (0x1.b80000p+5f * a2))) / (0x1.a40000p+6f + (a2 * (0x1.680000p+6f + (0x1.200000p+3f * a2)))));
  let r1 = select(base, (0x1.921fb4p+0f - base), (ay > ax));
  let r2 = select(r1, (0x1.921fb4p+1f - r1), (x < 0.0));
  if ((y < 0.0)) {
  return (0.0 - r2);
  } else {
  return r2;
  }
}
fn st_clamp01(x : f32) -> f32 {
  return max(0.0, min(0x1.000000p+0f, x));
}
fn st_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((st_clamp01(r) * 0x1.fe0000p+7f)) * 65536) + (i32((st_clamp01(g) * 0x1.fe0000p+7f)) * 256)) + i32((st_clamp01(b) * 0x1.fe0000p+7f)));
}
fn st_render(gid : i32, frame : i32) -> i32 {
  let px = f32(f32((gid - ((gid / st_width) * st_width))));
  let py = f32(f32((gid / st_width)));
  let dx = (px - 0x1.000000p+9f);
  let dy = (py - 0x1.800000p+8f);
  let r = sqrt(((dx * dx) + (dy * dy)));
  let spin = (f32(f32(frame)) / 0x1.180000p+5f);
  let a = (st_atan2(dy, dx) + spin);
  let rb = (0x1.ae0000p+7f + (0x1.540000p+6f * cos((a * 0x1.400000p+2f))));
  let d = (r - rb);
  if ((d > 0x1.800000p+2f)) {
  return st_pack((0x1.47ae14p-5f + (py / 0x1.f40000p+11f)), 0x1.999998p-5f, 0x1.47ae14p-4f);
  } else {
  if ((d > (0.0 - 0x1.800000p+2f))) {
  return st_pack(0x1.333332p-1f, 0x1.e66666p-1f, 0x1.000000p+0f);
  } else {
  let t = (f32(f32(frame)) / 0x1.400000p+4f);
  let sr = (0x1.000000p-1f + (0x1.000000p-1f * sin(((r * 0x1.999998p-5f) + t))));
  let sg = (0x1.000000p-1f + (0x1.000000p-1f * sin((((a * 0x1.800000p+1f) + (r * 0x1.eb851ep-6f)) + (t * 0x1.4cccccp+0f)))));
  let sb = (0x1.000000p-1f + (0x1.000000p-1f * sin(((a * 0x1.400000p+2f) - t))));
  return st_pack(sr, sg, sb);
  }
  }
}
@group(0) @binding(0) var<storage, read_write> stencil_step_outb_buf : array<i32>;
struct U_stencil_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_stencil_step : U_stencil_step;
@compute @workgroup_size(64)
fn stencil_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_stencil_step.frame;
  stencil_step_outb_buf[gid] = st_render(gid, frame);
}