// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const tr_width : i32 = 1024;
fn tr_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn tr_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn tr_sin(raw : i32) -> i32 {
  let a = tr_wrap(raw);
  if ((a <= 1570)) {
  return tr_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return tr_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - tr_sin_core((a - 3141)));
  } else {
  return (0 - tr_sin_core((6283 - a)));
  }
  }
  }
}
fn tr_cos(raw : i32) -> i32 {
  return tr_sin((raw + 1570));
}
fn tr_vx(frame : i32, k : i32) -> i32 {
  return (512 + ((tr_cos(((frame * 18) + (k * 2094))) * 250) / 1000));
}
fn tr_vy(frame : i32, k : i32) -> i32 {
  return (384 + ((tr_sin(((frame * 18) + (k * 2094))) * 250) / 1000));
}
fn tr_edge(ax : i32, ay : i32, bx : i32, by : i32, px : i32, py : i32) -> i32 {
  return (((px - ax) * (by - ay)) - ((py - ay) * (bx - ax)));
}
fn tr_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / tr_width) * tr_width));
  let py = (gid / tr_width);
  let ax = tr_vx(frame, 0);
  let ay = tr_vy(frame, 0);
  let bx = tr_vx(frame, 1);
  let by = tr_vy(frame, 1);
  let cx = tr_vx(frame, 2);
  let cy = tr_vy(frame, 2);
  let w0 = tr_edge(bx, by, cx, cy, px, py);
  let w1 = tr_edge(cx, cy, ax, ay, px, py);
  let w2 = tr_edge(ax, ay, bx, by, px, py);
  let inside = ((((w0 >= 0) && (w1 >= 0)) && (w2 >= 0)) || (((w0 <= 0) && (w1 <= 0)) && (w2 <= 0)));
  if ((inside == false)) {
  return 0;
  } else {
  let sum = ((w0 + w1) + w2);
  if ((sum == 0)) {
  return 0;
  } else {
  let r = ((w0 * 255) / sum);
  let g = ((w1 * 255) / sum);
  let b = ((w2 * 255) / sum);
  return (((r * 65536) + (g * 256)) + b);
  }
  }
}
@group(0) @binding(0) var<storage, read_write> triangle_step_outb_buf : array<i32>;
struct U_triangle_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_triangle_step : U_triangle_step;
@compute @workgroup_size(64)
fn triangle_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_triangle_step.frame;
  triangle_step_outb_buf[gid] = tr_render(gid, frame);
}