// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const va_width : i32 = 1024;
const va_half_w : i32 = 512;
fn va_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn va_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn va_sin(raw : i32) -> i32 {
  let a = va_wrap(raw);
  if ((a <= 1570)) {
  return va_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return va_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - va_sin_core((a - 3141)));
  } else {
  return (0 - va_sin_core((6283 - a)));
  }
  }
  }
}
fn va_cos(raw : i32) -> i32 {
  return va_sin((raw + 1570));
}
fn va_edge(ax : i32, ay : i32, bx : i32, by : i32, px : i32, py : i32) -> i32 {
  return (((px - ax) * (by - ay)) - ((py - ay) * (bx - ax)));
}
fn va_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / va_width) * va_width));
  let py = (gid / va_width);
  let ax = (512 + ((va_cos((frame * 18)) * 300) / 1000));
  let ay = (384 + ((va_sin((frame * 18)) * 300) / 1000));
  let bx = (512 + ((va_cos(((frame * 18) + 2094)) * 300) / 1000));
  let by = (384 + ((va_sin(((frame * 18) + 2094)) * 300) / 1000));
  let cx = (512 + ((va_cos(((frame * 18) + 4188)) * 300) / 1000));
  let cy = (384 + ((va_sin(((frame * 18) + 4188)) * 300) / 1000));
  let w0 = va_edge(bx, by, cx, cy, px, py);
  let w1 = va_edge(cx, cy, ax, ay, px, py);
  let w2 = va_edge(ax, ay, bx, by, px, py);
  let inside = ((((w0 >= 0) && (w1 >= 0)) && (w2 >= 0)) || (((w0 <= 0) && (w1 <= 0)) && (w2 <= 0)));
  if ((inside == false)) {
  return (((14 * 65536) + (16 * 256)) + 24);
  } else {
  let sum = ((w0 + w1) + w2);
  if ((sum == 0)) {
  return 0;
  } else {
  if ((px < va_half_w)) {
  let r = ((w0 * 255) / sum);
  let g = ((w1 * 255) / sum);
  let b = ((w2 * 255) / sum);
  return (((r * 65536) + (g * 256)) + b);
  } else {
  let u = ((w1 * 512) / sum);
  let v = ((w2 * 512) / sum);
  let chk = (((u / 40) + (v / 40)) - ((((u / 40) + (v / 40)) / 2) * 2));
  if ((chk == 0)) {
  return (((230 * 65536) + (230 * 256)) + 235);
  } else {
  return (((40 * 65536) + (44 * 256)) + 60);
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> vertexattr_step_outb_buf : array<i32>;
struct U_vertexattr_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_vertexattr_step : U_vertexattr_step;
@compute @workgroup_size(64)
fn vertexattr_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_vertexattr_step.frame;
  vertexattr_step_outb_buf[gid] = va_render(gid, frame);
}